### ISSUE TITLE
Error loading script: faceswap.py and swapper.py

### ISSUE THREAD

**Issue by cavaniho** [s0md3v/sd-webui-roop#1]
Error loading script: faceswap.py
Traceback (most recent call last):
  File "E:\sd ui\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\sd ui\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\sd ui\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 15, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "E:\sd ui\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

Error loading script: swapper.py
Traceback (most recent call last):
  File "E:\sd ui\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\sd ui\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\sd ui\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

**Comment by Gourieff** [comment]
@cavaniho if you're on Windows, try to install MS Visual Studio 2022 at first or just C++ packages through VS Build Tools

---

Extension works fine, **but** NSFW checker ruins everything, it detects NSFW even there, where is no NSFW, I turned it off inside cimage.py file

Everything works like a charm without it

IMAO you don't need to put StableDiffusionSafetyChecker inside your extension coz of hypersensitive algorithms, it checks as NSFW almost everything, that's the reason why no extension inside Automatic1111 uses NSFW checker

**Comment by chalkncheese** [comment]
Same issue here. I have Visual Studio 2022 and all required packages installed. The roop tab in the Automatic1111 web ui is not showing.

**Comment by Felzow47** [comment]
> 

same error for me

**Comment by Gourieff** [comment]
Just try to close Automatic1111 and start it again
If smth goes wrong, you must see errors 
And if the same issue, then:
Go to venv\Lib\site-packages folder, If you see folders with names starting from '~' - delete them
After that go to venv\Scripts
Run cmd from there
Type `activate`
Then:
python -m pip install -U pip
python -m pip install --force-reinstall insightface==0.7.3
Then:
cd ..\..\extensions\sd-webui-roop
python -m pip install -r requirements.txt

**Comment by Dreadfxl** [comment]
I had this, and all I did was opened a terminal and "pip install `pip install insightface`
Did this with every missing module it reported.
After that it all works perfectly

**Comment by arksam** [comment]
![Screenshot 2023-06-19 003704](https://github.com/s0md3v/sd-webui-roop/assets/21003627/d4969294-7a45-4515-b97c-1a8fbcfa87de)
Any Help ?

**Comment by JD1234JD1234** [comment]
I fixed it by installing visual studio community edition (https://visualstudio.microsoft.com/downloads/), when you're on the installer make sure to click all the 'python development' package and the 'development with c++' ones as they are not checked by default. says 30GB required but downloaded 6GB. restart PC and it works.

**Comment by s0md3v** [comment]
Closing as multiple solutions have been suggested.

**Comment by xDepredadorxD** [comment]
vaya a C:\stable-diffusion-webui\venv\Scripts
Ejecute cmd desde la barra de dirección 
activate python -m pip install -U pippython -m pip install insightface
