### ISSUE TITLE
NameError: name 'urllib' is not defined  and Error loading script: cimage.py

### ISSUE THREAD

**Issue by swumagic** [s0md3v/sd-webui-roop#10]
Error loading script: cimage.py
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\__init__.py", line 1, in <module>
    from .detector import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 35, in <module>
    download(model_url, model_path)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 15, in download
    request = urllib.request.urlopen(url)
NameError: name 'urllib' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Downloading the detection model to C:\Users\dckf\.models/detector.onnx
Error loading script: faceswap.py
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\faceswap.py", line 15, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
    from scripts.cimage import convert_to_sd
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\__init__.py", line 1, in <module>
    from .detector import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 35, in <module>
    download(model_url, model_path)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 15, in download
    request = urllib.request.urlopen(url)
NameError: name 'urllib' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

2023-06-19 14:32:09,178 - roop - INFO - roop v0.0.2
Downloading the detection model to C:\Users\dckf\.models/detector.onnx
Error loading script: swapper.py
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
    from scripts.cimage import convert_to_sd
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\__init__.py", line 1, in <module>
    from .detector import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 35, in <module>
    download(model_url, model_path)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 15, in download
    request = urllib.request.urlopen(url)
NameError: name 'urllib' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by s0md3v** [comment]
You are using an older version, this issue has been fixed. Update your extension.

**Comment by swumagic** [comment]
Error loading script: cimage.py
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\__init__.py", line 1, in <module>
    from .detector import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 35, in <module>
    download(model_url, model_path)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 15, in download
    request = urllib.request.urlopen(url)
NameError: name 'urllib' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error loading script: faceswap.py
Downloading the detection model to C:\Users\dckf\.models/detector.onnx
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\faceswap.py", line 15, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
    from scripts.cimage import convert_to_sd
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\__init__.py", line 1, in <module>
    from .detector import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 35, in <module>
    download(model_url, model_path)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 15, in download
    request = urllib.request.urlopen(url)
NameError: name 'urllib' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

2023-06-19 19:46:54,048 - roop - INFO - roop v0.0.2
Error loading script: swapper.py
Downloading the detection model to C:\Users\dckf\.models/detector.onnx
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
    from scripts.cimage import convert_to_sd
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\__init__.py", line 1, in <module>
    from .detector import detect
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 35, in <module>
    download(model_url, model_path)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 15, in download
    request = urllib.request.urlopen(url)
NameError: name 'urllib' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by swumagic** [comment]
I  Update  extension。6.18 version isOK（https://github.com/s0md3v/sd-webui-roop/commit/ef79abd735648d59a2ce9a02e01ca4d2bf4e4578）。 but 6.19version is bad。why？

**Comment by swumagic** [comment]
> You are using an older version, this issue has been fixed. Update your extension.

I Update extension before。6.18 version isOK（ef79abd735648d59a2ce9a02e01ca4d2bf4e4578）。 but 6.19version is bad。why？
