### ISSUE TITLE
TypeError: Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by donovanvaught** [s0md3v/sd-webui-roop#100]
followed all steps to install extension, installed visual studio, installed insightface, starting webui and get the error. tried downgrading protobuf and that didn't fix it. 

Full error

> venv "C:\Users\Don\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing requirements
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\Users\Don\stable-diffusion-webui\launch.py", line 38, in <module>
    main()
  File "C:\Users\Don\stable-diffusion-webui\launch.py", line 34, in main
    start()
  File "C:\Users\Don\stable-diffusion-webui\modules\launch_utils.py", line 330, in start
    import webui
  File "C:\Users\Don\stable-diffusion-webui\webui.py", line 28, in <module>
    import pytorch_lightning   # noqa: F401 # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
    from torchmetrics import Metric
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\torchmetrics\functional\__init__.py", line 82, in <module>
    from torchmetrics.functional.text.bleu import bleu_score
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\torchmetrics\functional\text\__init__.py", line 30, in <module>
    from torchmetrics.functional.text.bert import bert_score  # noqa: F401
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\torchmetrics\functional\text\bert.py", line 24, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\torchmetrics\functional\text\helper_embedding_metric.py", line 26, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\tensorflow\python\eager\context.py", line 28, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\Don\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
Downgrade the protobuf package to 3.20.x or lower.
Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by xfgexo** [comment]
same issue.

` File "D:\StableDifusion\stable-diffusion-webui\launch.py", line 361, in <module>
    start()
  File "D:\StableDifusion\stable-diffusion-webui\launch.py", line 352, in start
    import webui
  File "D:\StableDifusion\stable-diffusion-webui\webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "D:\StableDifusion\stable-diffusion-webui\modules\ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "D:\StableDifusion\stable-diffusion-webui\modules\sd_models.py", line 15, in <module>
    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config
  File "D:\StableDifusion\stable-diffusion-webui\modules\sd_disable_initialization.py", line 1, in <module>
    import ldm.modules.encoders.modules
  File "D:\StableDifusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 5, in <module>
    from transformers import T5Tokenizer, T5EncoderModel, CLIPTokenizer, CLIPTextModel
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\tensorflow\python\eager\context.py", line 28, in <module>
    from tensorflow.core.framework import function_pb2
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "D:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).`

**Comment by scutzzj** [comment]
This extension will check requirements when you start SD Web-UI, and it will modify the protobuf to 4.23.3 forcibly.

Just adding "protobuf==3.20.3" in the end of requirements.txt can solve thit problem.

Like this:
insightface==0.7.3
onnx==1.14.0
onnxruntime==1.15.0
opencv-python==4.7.0.72
ifnude
cython
protobuf==3.20.3

**Comment by donovanvaught** [comment]
> 

This solved the issue. Strange though that this would fix it but removing the extension folder, which has the offending txt file, wouldn't. There must be other files elsewhere in the install that also cause this problem.

**Comment by scutzzj** [comment]
> > 
> 
> This solved the issue, thank you. Strange though that this would fix it but removing the extension folder, which has the offending txt file, wouldn't. There must be other files elsewhere in the install that also cause this problem.

Do you mean that this error still exists after you remove the roop extension? I guess that it's because the versions of some of the python dependent libraries have been changed by roop. You can try to rollback their versions to make them suit for SD Web-UI.

**Comment by donovanvaught** [comment]
yes that's what I mean. any advice on how I might go about rolling back and what files to look for if I did want to do a full removal of roop? or maybe I'd be better off reinstalling everything :(
