### ISSUE TITLE
failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by sorryjack** [s0md3v/sd-webui-roop#102]
Updated latest version today (june 26 2023)

100%|███████████████████████████████████████████████████████████████████████████████| 20/20 [1:27:10<00:00, 261.52s/it]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}0/20 [1:25:15<00:00, 269.78s/it]
find model: C:\Users\Home/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Home/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Home/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Home/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Home/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
E:\sd.webui\system\python\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
Error running postprocess_batch: E:\sd.webui\webui\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "E:\sd.webui\webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "E:\sd.webui\webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
    result: ImageResult = swap_face(
  File "E:\sd.webui\webui\extensions\sd-webui-roop\scripts\swapper.py", line 127, in swap_face
    face_swapper = getFaceSwapModel(model_path)
  File "E:\sd.webui\webui\extensions\sd-webui-roop\scripts\swapper.py", line 40, in getFaceSwapModel
    FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
  File "E:\sd.webui\system\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "E:\sd.webui\system\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "E:\sd.webui\system\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "E:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "E:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from E:\sd.webui\webui\models\roop\inswapper_128.onnx failed:Protobuf parsing failed.

**Comment by sorryjack** [comment]
havent ever succeeded from the first use of "Roop". What should I do to fix this?

**Comment by BigZampano** [comment]
Same problem here after updating to automatic1111 version 1.4.0
