### ISSUE TITLE
Downloading the detection model to /home/rdteam/.ifnude/detector.onnx Error loading script: swapper.py

### ISSUE THREAD

**Issue by xuboot** [s0md3v/sd-webui-roop#107]
Downloading the detection model to /home/rdteam/.ifnude/detector.onnx
Error loading script: swapper.py
Traceback (most recent call last):
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by xuboot** [comment]
Downloading the classes list to /home/rdteam/.ifnude/classes
Error loading script: cimage.py
Traceback (most recent call last):
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/mnt/data/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/data/stable-diffusion-webui/extensions/sd-webui-roop/scripts/cimage.py", line 2, in <module>
    from ifnude import detect
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/site-packages/ifnude/__init__.py", line 1, in <module>
    from .detector import detect
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/site-packages/ifnude/detector.py", line 40, in <module>
    download(classes_url, classes_path)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/site-packages/ifnude/detector.py", line 16, in download
    request = urllib.request.urlopen(url)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/data/conda-env/conda/envs/sd-webui/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

**Comment by k186** [comment]
你如果用的集合包， 在设置里面代理设置 的代理服务器地址改为你的本地代理端口就可以了

**Comment by Tongzhou-Yu** [comment]
这里：https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx

**Comment by luzhengli** [comment]
two ways to slove your question：
1. download `https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx` and put it into `xxx/.ifnude/`
2. set agent to your webui and restart

**Comment by dizhenx** [comment]
> 你如果用的集合包， 在设置里面代理设置 的代理服务器地址改为你的本地代理端口就可以了

什么叫本地代理端口

**Comment by wangzijian1010** [comment]
> 这里：https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx

感谢bro bro一平安

**Comment by wangzijian1010** [comment]
> 

you can download in huggingface

**Comment by niwho** [comment]
[the same page contains  **`classes`** ](https://huggingface.co/s0md3v/nudity-checker/tree/main)
