### ISSUE TITLE
got an error while generating an image.

### ISSUE THREAD

**Issue by garin210** [s0md3v/sd-webui-roop#112]
I got this error while i'm generating an image. any solution? first, i thought it conflicted with the 'A detailer' extension so i turned it off but i still have the same problem.

2023-06-27 12:20:32,834 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process: D:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "D:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 462, in process
        if self.is_ad_enabled(*args_):
      File "D:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 156, in is_ad_enabled
        raise ValueError(dedent(message))
    ValueError:
    [-] ADetailer: Not enough arguments passed to ADetailer.
        input: ()

---
2023-06-27 12:20:32,836 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process: D:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: FaceSwapScript.process() missing 11 required positional arguments: 'img', 'enable', 'faces_index', 'model', 'face_restorer_name', 'face_restorer_visibility', 'upscaler_name', 'upscaler_scale', 'upscaler_visibility', 'swap_in_source', and 'swap_in_generated'

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 10.66it/s]
*** Error running postprocess_batch: D:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py4.96it/s]
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 177, in postprocess_batch
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: D:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 548, in postprocess_image
        if not self.is_ad_enabled(*args_):
      File "D:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 156, in is_ad_enabled
        raise ValueError(dedent(message))
    ValueError:
    [-] ADetailer: Not enough arguments passed to ADetailer.
        input: ()

---
*** Error running postprocess_image: D:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

**Comment by garin210** [comment]
it was conflicting with my text2video extension. without it it worked fine.

**Comment by eddiegolden** [comment]
> it was conflicting with my text2video extension. without it it worked fine.

That's right. Without my SCN text 2 video - it finally worked
