### ISSUE TITLE
ERROR with faceswap

### ISSUE THREAD

**Issue by NJFNN** [s0md3v/sd-webui-roop#114]
Hello! The ROOP is not working. It give me this error 

*** Error running postprocess_image: C:\SD\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py3.21it/s]
    Traceback (most recent call last):
      File "C:\SD\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\SD\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
        result: ImageResult = swap_face(
      File "C:\SD\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 123, in swap_face
        source_face = get_face_single(source_img, face_index=0)
      File "C:\SD\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 76, in get_face_single
        face_analyser = insightface.app.FaceAnalysis(name="buffalo_l", providers=providers)
      File "C:\SD\stable-diffusion-webui\venv\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
        assert 'detection' in self.models
    AssertionError

I read all closed issues and did not find solution to slove it. I need a help

**Comment by kaishanguai2012** [comment]
I had same problem,and already solved it.
download 5 models from https://github.com/deepinsight/insightface/tree/master/python-package
into C:\Users\Administrator\.insightface\models and unpack,then restart sd-webui,i will be ok.

**Comment by loveFeng** [comment]
linux
Downloading /root/.insightface/models/buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip
unzip /root/.insightface/models/buffalo_l.zip -d /root/.insightface/models/buffalo_l

**Comment by vfx999** [comment]
@NJFNN  Does it work?

**Comment by Wellbeing21** [comment]
no, it doesn't
