### ISSUE TITLE
macos eroor

### ISSUE THREAD

**Issue by chioulin** [s0md3v/sd-webui-roop#115]
Error running postprocess_batch: /Users/chioulinlee/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
Traceback (most recent call last):
  File "/Users/chioulinlee/stable-diffusion-webui/modules/scripts.py", line 462, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "/Users/chioulinlee/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 184, in postprocess_image
    result: ImageResult = swap_face(
  File "/Users/chioulinlee/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 109, in swap_face
    converted = convert_to_sd(target_img)
  File "/Users/chioulinlee/stable-diffusion-webui/extensions/sd-webui-roop/scripts/cimage.py", line 6, in convert_to_sd
    chunks = detect(img)
  File "/Users/chioulinlee/stable-diffusion-webui/venv/lib/python3.10/site-packages/ifnude/detector.py", line 46, in detect
    detection_model = onnxruntime.InferenceSession(model_path, providers=["CPUExecutionProvider"])
  File "/Users/chioulinlee/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Users/chioulinlee/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/chioulinlee/.ifnude/detector.onnx failed:Protobuf parsing failed.

**Comment by Anker-z** [comment]
试试这个 https://www.reddit.com/r/StableDiffusion/comments/14i2rr1/im_getting_this_big_ass_error_after_install_roop/

**Comment by chioulin** [comment]
It's installed. It's a runtime error.
