### ISSUE TITLE
roop error

### ISSUE THREAD

**Issue by wakakmomo** [s0md3v/sd-webui-roop#116]
Error running postprocess_batch: F:\stable-diffusion-webui\extensions\sd-webui-roop-main\scripts\faceswap.py  7.01it/s]
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 463, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "F:\stable-diffusion-webui\extensions\sd-webui-roop-main\scripts\faceswap.py", line 184, in postprocess_image
    result: ImageResult = swap_face(
  File "F:\stable-diffusion-webui\extensions\sd-webui-roop-main\scripts\swapper.py", line 109, in swap_face
    converted = convert_to_sd(target_img)
  File "F:\stable-diffusion-webui\extensions\sd-webui-roop-main\scripts\cimage.py", line 6, in convert_to_sd
    chunks = detect(img)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\ifnude\detector.py", line 46, in detect
    detection_model = onnxruntime.InferenceSession(model_path, providers=["CPUExecutionProvider"])
  File "F:\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\Admin\.ifnude/detector.onnx failed:Protobuf parsing failed.

**Comment by FixinHixon** [comment]
I'm also getting this error as of today

**Comment by avqeev** [comment]
You need to delete all extensions which say "unknown" under "update" After pressing check for update ofc
