### ISSUE TITLE
I after installing the roop extension, I am unable to launch SD webui

### ISSUE THREAD

**Issue by alexkorol** [s0md3v/sd-webui-roop#121]
I am running a fork of automatic1111 webui for Paperspace cloud gpu (https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace) and recently tried installing the roop extension, both through the extensions/available and extensions/install-from-url

## Expected behavior:

After placing sd-webui-roop into the extensions directory it should be available to use in a drop-down menu.

## Actual behaviour:

Webui doesn't restart afterwards and the code block 'Launch the Webui' generates this error when ran:

```
/storage/stable-diffusion/stable-diffusion-webui
Traceback (most recent call last):
  File "/storage/stable-diffusion/stable-diffusion-webui/webui.py", line 28, in <module>
    import pytorch_lightning   # noqa: F401 # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/__init__.py", line 82, in <module>
    from torchmetrics.functional.text.bleu import bleu_score
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/__init__.py", line 30, in <module>
    from torchmetrics.functional.text.bert import bert_score  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/bert.py", line 24, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/helper_embedding_metric.py", line 26, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "/usr/local/lib/python3.10/dist-packages/transformers/__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.10/dist-packages/transformers/dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/__init__.py", line 34, in <module>
    from .generic import (
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py", line 33, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```
I have to remove the sd-webui-roop folder, restart the machine and run all the code blocks for webui to work again.

**Comment by AnnieBunnieX** [comment]
Try reinstalling the venv, That might help you.

**Comment by MatoMA** [comment]
You can try the workaround 2: Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python.
If you are on Linux, you can add
`export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`
in the file **webui-user.sh**

**Comment by Cooldod990** [comment]
Roop needs Visual Stidio installed. I have no idea, how to install it on paperspace, its installation package only for windows

**Comment by cyleonebk** [comment]
> 您可以尝试解决方法 2：设置 PROTOCOL_BUFFERS_PYTHON_IMPLMENTATION=python。 如果您使用的是 Linux，则可以 `export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` 在文件**webui-user.sh中添加**

this right

**Comment by moo611** [comment]
> You can try the workaround 2: Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python. If you are on Linux, you can add `export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` in the file **webui-user.sh**

solved my problem, thanks
