### ISSUE TITLE
how about "inswapper_128.onnx failed:Protobuf parsing failed."

### ISSUE THREAD

**Issue by chuju320** [s0md3v/sd-webui-roop#130]
err:
** Error running postprocess_image: I:\StableDiffusion\miaoshouai-sd-webui-v230222full\miaoshouai-sd-webui-v230222full\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "I:\StableDiffusion\miaoshouai-sd-webui-v230222full\miaoshouai-sd-webui-v230222full\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "I:\StableDiffusion\miaoshouai-sd-webui-v230222full\miaoshouai-sd-webui-v230222full\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
        result: ImageResult = swap_face(
      File "I:\StableDiffusion\miaoshouai-sd-webui-v230222full\miaoshouai-sd-webui-v230222full\extensions\sd-webui-roop\scripts\swapper.py", line 127, in swap_face
        face_swapper = getFaceSwapModel(model_path)
      File "I:\StableDiffusion\miaoshouai-sd-webui-v230222full\miaoshouai-sd-webui-v230222full\extensions\sd-webui-roop\scripts\swapper.py", line 40, in getFaceSwapModel
        FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
      File "I:\StableDiffusion\miaoshouai-sd-webui-v230222full\miaoshouai-sd-webui-v230222full\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "I:\StableDiffusion\miaoshouai-sd-webui-v230222full\miaoshouai-sd-webui-v230222full\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "I:\StableDiffusion\miaoshouai-sd-webui-v230222full\miaoshouai-sd-webui-v230222full\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "I:\StableDiffusion\miaoshouai-sd-webui-v230222full\miaoshouai-sd-webui-v230222full\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "I:\StableDiffusion\miaoshouai-sd-webui-v230222full\miaoshouai-sd-webui-v230222full\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from I:\StableDiffusion\miaoshouai-sd-webui-v230222full\miaoshouai-sd-webui-v230222full\models\roop\inswapper_128.onnx failed:Protobuf parsing failed.

**Comment by iielse** [comment]
same

**Comment by princecrown1019** [comment]
Me too, same issue. looking for solutions!
