### ISSUE TITLE
Error??? Help

### ISSUE THREAD

**Issue by avqeev** [s0md3v/sd-webui-roop#132]
`Launching Web UI with arguments: --xformers --autolaunch --no-half-vae
hello some more!
hello some more!
hello some more!
hello some more!
[-] ADetailer initialized. version: 23.6.4, num models: 8
2023-07-01 19:54:05,566 - ControlNet - INFO - ControlNet v1.1.227
ControlNet preprocessor location: E:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-07-01 19:54:05,794 - ControlNet - INFO - ControlNet v1.1.227
2023-07-01 19:54:12,494 - roop - INFO - roop v0.0.2
2023-07-01 19:54:12,496 - roop - INFO - roop v0.0.2
Loading weights [f4de303304] from E:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\AbsoluteMixV5-0.5.safetensors
Creating model from config: E:\StableDiffusion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(10): bad-artist, bad-artist-anime, bad-hands-5, bad-image-v2-39000, bad_prompt, bad_prompt_version2, EasyNegativeV2, MangaHentaiStyleConceptv2, negative_hand-neg, ng_deepnegative_v1_75t
Textual inversion embeddings skipped(2): nartfixer, nfixer
Model loaded in 14.8s (load weights from disk: 0.5s, create model: 1.1s, apply weights to model: 11.3s, apply half(): 0.6s, move model to device: 0.9s, load textual inversion embeddings: 0.2s, calculate empty prompt: 0.1s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 36.1s (import torch: 2.7s, import gradio: 2.5s, import ldm: 0.8s, other imports: 2.5s, setup codeformer: 0.1s, list SD models: 0.5s, load scripts: 11.0s, create ui: 15.5s, gradio launch: 0.5s).
preload_extensions_git_metadata for 28 extensions took 3.86s
2023-07-01 19:56:42,429 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process: E:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "E:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "E:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 462, in process
        if self.is_ad_enabled(*args_):
      File "E:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 157, in is_ad_enabled
        raise ValueError(dedent(message))
    ValueError:
    [-] ADetailer: Invalid arguments passed to ADetailer.
        input: ()

---
*** Error running process: E:\StableDiffusion\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "E:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 21 required positional arguments: 'enabled', 'method', 'overwrite_size', 'keep_input_size', 'image_width', 'image_height', 'tile_width', 'tile_height', 'overlap', 'tile_batch_size', 'upscaler_name', 'scale_factor', 'noise_inverse', 'noise_inverse_steps', 'noise_inverse_retouch', 'noise_inverse_renoise_strength', 'noise_inverse_renoise_kernel', 'control_tensor_cpu', 'enable_bbox_control', 'draw_background', and 'causal_layers'

---
*** Error running process: E:\StableDiffusion\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
    Traceback (most recent call last):
      File "E:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'encoder_tile_size', 'decoder_tile_size', 'vae_to_gpu', 'fast_decoder', 'fast_encoder', and 'color_fix'

---
*** Error running process: E:\StableDiffusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "E:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 18 required positional arguments: 'is_enabled', 'is_combinatorial', 'combinatorial_batches', 'is_magic_prompt', 'is_feeling_lucky', 'is_attention_grabber', 'min_attention', 'max_attention', 'magic_prompt_length', 'magic_temp_value', 'use_fixed_seed', 'unlink_seed_from_prompt', 'disable_negative_prompt', 'enable_jinja_templates', 'no_image_generation', 'max_generations', 'magic_model', and 'magic_blocklist_regex'

---
2023-07-01 19:56:42,434 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process: E:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py
    Traceback (most recent call last):
      File "E:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 13 required positional arguments: 'enabled', 'multiply', 'weight', 'understand', 'layers', 'apply_to', 'start_steps', 'max_steps', 'up', 'up_aa', 'down', 'down_aa', and 'intp'

---
*** Error running process: E:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "E:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: FaceSwapScript.process() missing 11 required positional arguments: 'img', 'enable', 'faces_index', 'model', 'face_restorer_name', 'face_restorer_visibility', 'upscaler_name', 'upscaler_scale', 'upscaler_visibility', 'swap_in_source', and 'swap_in_generated'`

**Comment by avqeev** [comment]
When trying to upscale annything or use img2img

**Comment by avqeev** [comment]
Oh for everyone here, i fixed it by deleting all extension which said "Unknown" under "update" After clicking check for update ofc
