### ISSUE TITLE
inswapper_128.onnx is in correct directory, but not detected

### ISSUE THREAD

**Issue by Raivshard** [s0md3v/sd-webui-roop#133]
`2023-07-01 16:40:38,442 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/s0md3v/sd-webui-roop/`

So, the extension installs this specifc file to extensions\sd-webui-roop\models\roop, I checked this after seeing both this error in the log and "Model not found, please download one and reload automatic 1111" in the UI.

I have restarted the webui twice.

Clearly something is incorrect. Is it supposed to go in  [main webuifolder]\\models\roop instead? If so, that should be done by the install.

**Comment by Raivshard** [comment]
I just manually moved the file and now it works fine. You really should fix this. Either change the reference to the extension folder, or install the file to webuifolder\models\roop

**Comment by Someonetoldme584** [comment]
moved the file wherE ?  same problem

**Comment by gohan2091** [comment]
It seems I have duplicate locations where this inswapper_128.onnx goes:

1) \automatic\extensions\sd-webui-roop\models\roop
2) \automatic\models\roop

Which is the correct location? Your installation instructions say it's the 2nd location so why is it also in the first?

**Comment by Lexcess** [comment]
I was just trying this out and there seems to be something up with the code. If I hardcode the model path it works, otherwise it doesn't (on Windows at least). I see that last week the line in question was changed for Windows, so I suspect whatever the fix was didn't work.

If it helps, I took line 22 in Faceswap.py

`"models_path = os.path.join(scripts.basedir(), "models" + os.path.sep + "roop" + os.path.sep + "*")"`

and changed it to:

`models_path = r'C:\repos\automatic\extensions\sd-webui-roop\models\roop\*' # os.path.join(scripts.basedir(), "models" + os.path.sep + "roop" + os.path.sep + "*")`

**Comment by VitaliyAT** [comment]
The same problem - file in both places - use VD instead SD but they should be the same in this points

**Comment by naitedj** [comment]
the same, the file is where it is needed, but it gives an error (I would like to install.

Error loading script: faceswap.py
Traceback (most recent call last):
  File "G:\neiro\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "G:\neiro\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\neiro\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "G:\neiro\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

2023-07-31 11:39:24,079 - roop - INFO - roop v0.0.2
Error loading script: swapper.py
Traceback (most recent call last):
  File "G:\neiro\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "G:\neiro\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\neiro\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'
