### ISSUE TITLE
roop not working error when running sd-webui

### ISSUE THREAD

**Issue by leige666nb** [s0md3v/sd-webui-roop#137]
roop not working error when running sd-webui

*** Command: "D:\Desktop\stable-diffusion-webui\venv\Scripts\python.exe" "D:\Desktop\stable-diffusion-webui\extensions\sd-webui-roop\install.py"
*** Error code: 1
*** stdout: Checking roop requirements
*** Install
*** Installing sd-webui-roop requirement:
*** Couldn't install sd-webui-roop requirement: .
*** Command: "D:\Desktop\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install  --prefer-binary
*** Error code: 1
*** stderr: ERROR: You must give at least one requirement to install (see "pip help install")
***
*** Warning: Failed to install , roop will not work.
***
*** stderr: Traceback (most recent call last):
***   File "D:\Desktop\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 54, in <module>
***     raise e
***   File "D:\Desktop\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 36, in <module>
***     launch.run_pip(
***   File "D:\Desktop\stable-diffusion-webui\modules\launch_utils.py", line 130, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "D:\Desktop\stable-diffusion-webui\modules\launch_utils.py", line 107, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install sd-webui-roop requirement: .
*** Command: "D:\Desktop\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install  --prefer-binary
*** Error code: 1
*** stderr: ERROR: You must give at least one requirement to install (see "pip help install")
***

**Comment by leige666nb** [comment]
In order to avoid pip download conflicts, I modified the roop installation requirements file, and successfully opened sd-webui but the roop drop-down menu did not appear.

insightface==0.7.3
onnx==1.12.0
onnxruntime==1.15.1
opencv-python==4.7.0.72
ifnude
cython

**Comment by leige666nb** [comment]
@s0md3v 
Problem is not solved.  please reopen pls!
