### ISSUE TITLE
Error running postprocess_batch

### ISSUE THREAD

**Issue by Millan-K** [s0md3v/sd-webui-roop#138]
Since the new A1111 update i get this error: 
Any idea what could go wrong ?

*** Error running postprocess_batch: C:\a1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py▎                              | 51/68 [00:12<00:03,  4.30it/s]
    Traceback (most recent call last):
      File "C:\a1111\stable-diffusion-webui\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "C:\a1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 177, in postprocess_batch
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

**Comment by NathanSlim** [comment]
I've been having the same issue. Updated to the latest commit as I saw another posting of this issue got closed but unfortunately no luck. 

The above seems to be only the end of the log, in case s0md3v can't reproduce the issue, this is the log from the beginning of the generation:

`*** Error running process: C:\Users\aux_n\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "C:\Users\aux_n\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: FaceSwapScript.process() missing 11 required positional arguments: 'img', 'enable', 'faces_index', 'model', 'face_restorer_name', 'face_restorer_visibility', 'upscaler_name', 'upscaler_scale', 'upscaler_visibility', 'swap_in_source', and 'swap_in_generated'

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.49it/s]
*** Error running postprocess_batch: C:\Users\aux_n\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "C:\Users\aux_n\stable-diffusion-webui\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "C:\Users\aux_n\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 177, in postprocess_batch
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: C:\Users\aux_n\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "C:\Users\aux_n\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\aux_n\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'`

I've tried various forks and applying an older version but still having no luck so don't think it's particularly an issue roop has introduced. 

Thanks for all your hard work either way!

**Comment by Vrahel88** [comment]
Having the same issue. I updated my extensions and since then I get this error. I reinstalled Roop but no luck. It seems that one of the other updates caused this, but i did not log the extensions I updated 😭

**Comment by Vrahel88** [comment]
@Millan-K @NathanSlim 

I found that it was the extention "SD-CN-Animation" causing the problems. After deactivating this extension everything worked fine.

**Comment by NathanSlim** [comment]
> @Millan-K @NathanSlim
> 
> I found that it was the extention "SD-CN-Animation" causing the problems. After deactivating this extension everything worked fine.

You're a beautiful human being. This resolved the issue, Thank you :D
