### ISSUE TITLE
Unable to start，Help me

### ISSUE THREAD

**Issue by MEOGit** [s0md3v/sd-webui-roop#141]
[-] ADetailer initialized. version: 23.7.2, num models: 9
2023-07-04 22:12:47,099 - ControlNet - INFO - ControlNet v1.1.229
ControlNet preprocessor location: E:\MEO\Stable Diffusion\extensions\sd-webui-controlnet\annotator\downloads
2023-07-04 22:12:47,226 - ControlNet - INFO - ControlNet v1.1.229
*** Error loading script: cimage.py
    Traceback (most recent call last):
      File "E:\MEO\Stable Diffusion\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\MEO\Stable Diffusion\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\MEO\Stable Diffusion\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "E:\MEO\Stable Diffusion\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\MEO\Stable Diffusion\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\MEO\Stable Diffusion\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "E:\MEO\Stable Diffusion\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
2023-07-04 22:12:47,397 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "E:\MEO\Stable Diffusion\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\MEO\Stable Diffusion\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\MEO\Stable Diffusion\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by NathanSlim** [comment]
if you've done the `pip install "packagename"` then they may have installed here: C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages

Just copy the folders or files for each of the modules over to : C:\Users\username\stable-diffusion-webui\venv\Lib\site-packages

fixed this issue for me

**Comment by MEOGit** [comment]
Different locations, find Python 310  site packages
Still unresolved

**Comment by gunjahman** [comment]
[Gourieff] You are a God! After many days and many attempts and many proposed solutions, yours finally worked!
Thank you so much!

**Comment by zszroses** [comment]
@Gourieff Thank you, God, you saved me
