### ISSUE TITLE
TypeError: Landmark.get() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by joeyhe88** [s0md3v/sd-webui-roop#149]
Can anyone help me solve this problem
*** Error running postprocess_image: G:\novelai-webui-aki-v2\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "G:\novelai-webui-aki-v2\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "G:\novelai-webui-aki-v2\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
        result: ImageResult = swap_face(
      File "G:\novelai-webui-aki-v2\extensions\sd-webui-roop\scripts\swapper.py", line 132, in swap_face
        result = face_swapper.get(result, target_face, source_face)
    TypeError: Landmark.get() takes 3 positional arguments but 4 were given

**Comment by Zalmighty** [comment]
Same problem

**Comment by uubuge** [comment]
![image](https://github.com/s0md3v/sd-webui-roop/assets/33352557/b266d9f8-c51c-4401-ba17-bc11b55557c2)
select this
