### ISSUE TITLE
img2img NOT working

### ISSUE THREAD

**Issue by XTRMsavage** [s0md3v/sd-webui-roop#169]
I am getting this error 
"*** Error running postprocess_image: D:\stable-diffusion-v14\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-v14\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\stable-diffusion-v14\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
        result: ImageResult = swap_face(
      File "D:\stable-diffusion-v14\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 132, in swap_face
        result = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'"

Please help!

**Comment by swumagic** [comment]
If you encounter 'NoneType' object has no attribute 'get' error,   download the [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx) model and put it inside  <webui_dir> /models/roop/ directory.

**Comment by proevgenii** [comment]
Hey @swumagic 
I have met the same issue, and ONNX model 'inswapper_128.onnx' is already in the required directory `/stable-diffusion-webui/models/roop/`

Here is full log
```
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}████████████████████████████| 20/20 [00:24<00:00,  1.29s/it]
find model: /Users/proevgenii/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/proevgenii/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/proevgenii/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/proevgenii/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/proevgenii/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
/Users/proevgenii/sb/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/proevgenii/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/proevgenii/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/proevgenii/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/proevgenii/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/proevgenii/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
*** Error running postprocess_image: /Users/proevgenii/sb/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
    Traceback (most recent call last):
      File "/Users/proevgenii/sb/stable-diffusion-webui/modules/scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/Users/proevgenii/sb/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 184, in postprocess_image
        result: ImageResult = swap_face(
      File "/Users/proevgenii/sb/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 132, in swap_face
        result = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Gourieff** [comment]
Do you guys use it through API?
I encountered this error but don't remember clearly what was the reason
But if you use API - there may be arguments mismatch that can cause this error

**Comment by VitaliyAT** [comment]
+1
1) no any --api in bat files
2) all installed according instructions, visual studio, model onnx in right place - is boot process roop don't see any model and say it in UI after.

Full log of booting
```
venv "C:\[Ai]\1111\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
Installing requirements
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
2023-07-20 22:04:26,523 - roop - INFO - roop v0.0.2
2023-07-20 22:04:26,524 - roop - INFO - roop v0.0.2
Loading weights [6ce0161689] from C:\[Ai]\1111\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
2023-07-20 22:04:27,149 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/s0md3v/sd-webui-roop/
2023-07-20 22:04:27,327 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/s0md3v/sd-webui-roop/
preload_extensions_git_metadata for 8 extensions took 0.09s
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 3.7s (import torch: 1.0s, import gradio: 0.5s, import ldm: 0.2s, other imports: 0.7s, load scripts: 0.7s, create ui: 0.4s, gradio launch: 0.1s).
Creating model from config: C:\[Ai]\1111\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: Doggettx... done.
Textual inversion embeddings loaded(0):
Model loaded in 2.6s (load weights from disk: 0.5s, create model: 0.3s, apply weights to model: 0.7s, apply half(): 0.4s, move model to device: 0.5s).
```

**Comment by Xelawk** [comment]
> Do you guys use it through API? I encountered this error but don't remember clearly what was the reason But if you use API - there may be arguments mismatch that can cause this error

how to solve it, what's the exactly arguments?
