### ISSUE TITLE
 AttributeError: 'FaceSwapScript' object has no attribute 'enable'

### ISSUE THREAD

**Issue by marco-qu** [s0md3v/sd-webui-roop#172]
*** Error running postprocess_batch: D:\work\ai\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.pyt/s]
    Traceback (most recent call last):
      File "D:\work\ai\stable-diffusion-webui\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "D:\work\ai\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 177, in postprocess_batch
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: D:\work\ai\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\work\ai\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\work\ai\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

**Comment by Gourieff** [comment]
The conflict with another extension
If you have the "SD-CN-Animation" extension enabled - disable it

**Comment by marco-qu** [comment]
> 

No, I don't have this extension.

**Comment by Gourieff** [comment]
Try to disable other extensions one-by-one (except the built-in ones)

**Comment by tr33449999** [comment]
Did you solve the problem? I have the same problem here.
