### ISSUE TITLE
Problems with Roop extension

### ISSUE THREAD

**Issue by lotnick** [s0md3v/sd-webui-roop#177]
Hello, I just Installed Roop but I have a lot of problems. Anybody? Thanks!!!

2023-07-18 11:36:52.4434218 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1827 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
Error loading script: faceswap.py
Traceback (most recent call last):
  File "C:\Users\lotni\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lotni\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 15, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 12, in <module>
    import insightface
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 8, in <module>
    from .domain_adaptation import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 6, in <module>
    from qudida import DomainAdapter
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\qudida\__init__.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\__init__.py", line 80, in <module>
    from . import _distributor_init  # noqa: F401
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\_distributor_init.py", line 21, in <module>    WinDLL(op.abspath(vcomp140_dll_filename))
  File "C:\Users\lotni\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.

2023-07-18 11:36:52,512 - Roop-GE - INFO - Roop-GE v0.2.1
Error loading script: swapper.py
Traceback (most recent call last):
  File "C:\Users\lotni\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lotni\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 12, in <module>
    import insightface
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 8, in <module>
    from .domain_adaptation import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 6, in <module>
    from qudida import DomainAdapter
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\qudida\__init__.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\__init__.py", line 80, in <module>
    from . import _distributor_init  # noqa: F401
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\_distributor_init.py", line 21, in <module>    WinDLL(op.abspath(vcomp140_dll_filename))
  File "C:\Users\lotni\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by lotnick** [comment]
Thank You, I'll try. I have other two roop extensions but they are unchecked in extension tab. I'll try to delete them

**Comment by lotnick** [comment]
I did as you suggested, but the problem remains. I don't know whether to reinstall everything from scratch. Thank you

**Comment by adde88** [comment]
Try installing **Visual C++ Redistributable for Visual Studio 2015**, and then after that re-install scikit-learn into your python environment (_local, or venv_) by using pip: 
**`pip install scikit-learn -U`**

I only recommend attempting it, in that order, because vscomp14.dll belongs to that Visual C++ package, and "_sklearn.libs_" belongs to **sciktit-learn**

**Comment by lotnick** [comment]
Thank You, I'll try

**Comment by lotnick** [comment]
> Try installing **Visual C++ Redistributable for Visual Studio 2015**, and then after that re-install **scikit-learn** into your python environment (_local, or venv_) by using pip: **`pip install scikit-learn -U`**
> 
> I only recommend attempting it, in that order, because vscomp14.dll belongs to that Visual C++ package, and "_sklearn.libs_" belongs to **sciktit-learn**

 Nope, Windows says they are already installed
