### ISSUE TITLE
Where should I download this detector.onnx

### ISSUE THREAD

**Issue by realclone1** [s0md3v/sd-webui-roop#18]
2023-06-20 04:28:45,894 - roop - INFO - roop v0.0.2
Downloading the detection model to C:\Users\Administrator\.ifnude/detector.onnx
Error loading script: swapper.py
Traceback (most recent call last):
  File "C:\AI\python\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\AI\python\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\AI\python\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\AI\python\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\AI\python\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\AI\python\lib\http\client.py", line 976, in send
    self.connect()
  File "C:\AI\python\lib\http\client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\AI\python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\AI\python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\AI\python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by s0md3v** [comment]
This is a network issue, simply try again.

I will add a retrying functionality in the code soon.

**Comment by yeeyou** [comment]
Many people has network issue especially in China. 
recommand to put the model into readme like the 128xxx.onnx
https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx

**Comment by h93910** [comment]
> Many people has network issue especially in China. recommand to put the model into readme like the 128xxx.onnx https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx

sad china , thx bro
