### ISSUE TITLE
Model not found error 

### ISSUE THREAD

**Issue by killamonis** [s0md3v/sd-webui-roop#180]
I'm getting the following error that the model can't be found. I've placed the model in `stable-diffusion-webui/models/roop/inswapper_128.onnx` but it's checking in the scripts folder for some reason?

```
*** Error running postprocess_image: /workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
Traceback (most recent call last):
File "/workspace/stable-diffusion-webui/modules/scripts.py", line 514, in postprocess_image
script.postprocess_image(p, pP, *script_args)
File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py",line 184, in postprocess_image
result: ImageResult = swap_face(
File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 127, in swap_face
face_swapper = getFaceSwapModel(model_path)
File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py",line 40, in getFaceSwapModel
FS_MODEL = insightface.model_zoo.get_model(model_path, providers-providers)
File "/workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py",line 91, in get_
assert osp.exists(model_file), 'model_file % should exist "%model_file
AssertionError: model_file /workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/inswapper_128.on should exist
```

**Comment by FilipeF12** [comment]
check for updates in extensions
