### ISSUE TITLE
Error running postprocess_image: /Users/apple/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py

### ISSUE THREAD

**Issue by 705284036** [s0md3v/sd-webui-roop#188]
Closing server running on port: 7860
2023-07-26 02:35:52,092 - roop - INFO - roop v0.0.2
2023-07-26 02:35:52,094 - roop - INFO - roop v0.0.2
preload_extensions_git_metadata for 10 extensions took 0.29s
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 1.2s (load scripts: 0.3s, create ui: 0.7s, gradio launch: 0.2s).
*** Error running process: /Users/apple/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
    Traceback (most recent call last):
      File "/Users/apple/stable-diffusion-webui/modules/scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: FaceSwapScript.process() missing 11 required positional arguments: 'img', 'enable', 'faces_index', 'model', 'face_restorer_name', 'face_restorer_visibility', 'upscaler_name', 'upscaler_scale', 'upscaler_visibility', 'swap_in_source', and 'swap_in_generated'

---
100%|█████████████████████████████████████████████| 3/3 [00:26<00:00,  8.96s/it]
*** Error running postprocess_batch: /Users/apple/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
    Traceback (most recent call last):
      File "/Users/apple/stable-diffusion-webui/modules/scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "/Users/apple/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 177, in postprocess_batch
        if self.enable:
           ^^^^^^^^^^^
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: /Users/apple/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
    Traceback (most recent call last):
      File "/Users/apple/stable-diffusion-webui/modules/scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/Users/apple/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
           ^^^^^^^^^^^
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
Total progress: 100%|█████████████████████████████| 3/3 [00:25<00:00,  8.36s/it]
Total progress: 100%|█████████████████████████████| 3/3 [00:25<00:00,  5.44s/it]

Unable to use ROOP and did not change face. How to adjust these parameters

**Comment by zszroses** [comment]
me too
