### ISSUE TITLE
Install loop and inswapper on Linux_ 128. The onnx model is located in/usr/local/table differentiation webui/models/room/inswapper_ 128.onnx, prompt face when calling API_ Swapper, this variable is None

### ISSUE THREAD

**Issue by Aiyx0628** [s0md3v/sd-webui-roop#196]
2023-07-31 03:31:19 | Traceback (most recent call last):
2023-07-31 03:31:19 | File "/usr/local/stable-diffusion-webui/modules/scripts.py", line 514, in postprocess_image
2023-07-31 03:31:19 | script.postprocess_image(p, pp, *script_args)
2023-07-31 03:31:19 | File "/usr/local/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 184, in postprocess_image
2023-07-31 03:31:19 | result: ImageResult = swap_face(
2023-07-31 03:31:19 | File "/usr/local/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 132, in swap_face
2023-07-31 03:31:19 | result = face_swapper.get(result, target_face, source_face)
2023-07-31 03:31:19 | AttributeError: 'NoneType' object has no attribute 'get'

**Comment by xxtyy** [comment]
I encountered the same problem, did you solve it?
