### ISSUE TITLE
i install the extension and restart ui why i cant find the roop tab?

### ISSUE THREAD

**Issue by PuddingJoker** [s0md3v/sd-webui-roop#20]
<img width="1409" alt="image" src="https://github.com/s0md3v/sd-webui-roop/assets/81021391/07313540-5358-4080-bb52-e977ea219b9b">

**Comment by lhucklen** [comment]
Traceback (most recent call last):
  File "C:\sd\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\sd\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\sd\stable-diffusion-webui\extensions\sd-webui-roop-uncensored\scripts\swapper.py", line 12, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

**Comment by PuddingJoker** [comment]
> ModuleNotFoundError: No module named 'insightface'

yep,i got this error：ModuleNotFoundError: No module named 'insightface' ，how can i fix it?

**Comment by PuddingJoker** [comment]
> Traceback (most recent call last): File "C:\sd\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "C:\sd\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "C:\sd\stable-diffusion-webui\extensions\sd-webui-roop-uncensored\scripts\swapper.py", line 12, in import insightface ModuleNotFoundError: No module named 'insightface'

thanks! i already resolved this problem!
