### ISSUE TITLE
Roop seems not to be working 

### ISSUE THREAD

**Issue by raiyan22** [s0md3v/sd-webui-roop#202]
This is what my cmd says

venv "C:\zero\stablediff\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements

Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72

Launching Web UI with arguments: --xformers --autolaunch --medvram
2023-08-07 02:16:18,023 - ControlNet - INFO - ControlNet v1.1.234
ControlNet preprocessor location: C:\zero\stablediff\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-08-07 02:16:18,104 - ControlNet - INFO - ControlNet v1.1.234
2023-08-07 02:16:18,580 - roop - INFO - roop v0.0.2
2023-08-07 02:16:18,581 - roop - INFO - roop v0.0.2
Loading weights [9aba26abdf] from C:\zero\stablediff\stable-diffusion-webui\models\Stable-diffusion\deliberate_v2.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: C:\zero\stablediff\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Startup time: 7.9s (import torch: 1.9s, import gradio: 1.0s, import ldm: 0.6s, other imports: 1.1s, load scripts: 2.1s, create ui: 0.4s, gradio launch: 0.7s).
preload_extensions_git_metadata for 11 extensions took 2.53s
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(1): aoshen
Model loaded in 5.7s (load weights from disk: 0.7s, create model: 1.4s, apply weights to model: 1.5s, apply half(): 1.0s, calculate empty prompt: 1.1s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.44it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  2.96it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.77it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.78it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.75it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.75it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.84it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.81it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  2.99it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  2.99it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.04it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.06it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  2.87it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.85it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  2.96it/s]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}| 20/20 [00:05<00:00,  3.13it/s]
find model: C:\Users\raiya/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\raiya/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\raiya/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\raiya/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\raiya/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
C:\zero\stablediff\stable-diffusion-webui\venv\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
*** Error running postprocess_image: C:\zero\stablediff\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "C:\zero\stablediff\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\zero\stablediff\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
        result: ImageResult = swap_face(
      File "C:\zero\stablediff\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 127, in swap_face
        face_swapper = getFaceSwapModel(model_path)
      File "C:\zero\stablediff\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 40, in getFaceSwapModel
        FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
      File "C:\zero\stablediff\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "C:\zero\stablediff\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "C:\zero\stablediff\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\zero\stablediff\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\zero\stablediff\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\zero\stablediff\stable-diffusion-webui\models\roop\inswapper_128.onnx failed:Protobuf parsing failed.

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.99it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  3.13it/s]

**Comment by raiyan22** [comment]
Trying to resolve the issue using [this](https://github.com/s0md3v/sd-webui-roop/issues/29)

**Comment by raiyan22** [comment]
Issue solved. Thank you! Help is [here](https://github.com/s0md3v/sd-webui-roop/issues/29)
