### ISSUE TITLE
Why did I report this error when I started Stable Diffusion after installing sd-webui-roop?

### ISSUE THREAD

**Issue by zhengdong890** [s0md3v/sd-webui-roop#206]
Downloading the classes list to /home/sd/.ifnude/classes
*** Error loading script: cimage.py
    Traceback (most recent call last):
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1282, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1328, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1277, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1037, in _send_output
        self.send(msg)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 975, in send
        self.connect()
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1454, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/ssl.py", line 513, in wrap_socket
        return self.sslsocket_class._create(
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/ssl.py", line 1071, in _create
        self.do_handshake()
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/ssl.py", line 1342, in do_handshake
        self._sslobj.do_handshake()
    ConnectionResetError: [Errno 104] Connection reset by peer

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/sd/stable-diffusion-webui/extensions/sd-webui-roop/scripts/cimage.py", line 2, in <module>
        from ifnude import detect
      File "/home/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/ifnude/__init__.py", line 1, in <module>
        from .detector import detect
      File "/home/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/ifnude/detector.py", line 40, in <module>
        download(classes_url, classes_path)
      File "/home/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/ifnude/detector.py", line 16, in download
        request = urllib.request.urlopen(url)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 519, in open
        response = self._open(req, data)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 496, in _call_chain
        result = func(*args)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

---
Downloading the classes list to /home/sd/.ifnude/classes
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1282, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1328, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1277, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1037, in _send_output
        self.send(msg)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 975, in send
        self.connect()
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1454, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/ssl.py", line 513, in wrap_socket
        return self.sslsocket_class._create(
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/ssl.py", line 1071, in _create
        self.do_handshake()
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/ssl.py", line 1342, in do_handshake
        self._sslobj.do_handshake()
    ConnectionResetError: [Errno 104] Connection reset by peer

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/sd/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "/home/sd/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 14, in <module>
        from scripts.cimage import convert_to_sd
      File "/home/sd/stable-diffusion-webui/extensions/sd-webui-roop/scripts/cimage.py", line 2, in <module>
        from ifnude import detect
      File "/home/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/ifnude/__init__.py", line 1, in <module>
        from .detector import detect
      File "/home/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/ifnude/detector.py", line 40, in <module>
        download(classes_url, classes_path)
      File "/home/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/ifnude/detector.py", line 16, in download
        request = urllib.request.urlopen(url)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 519, in open
        response = self._open(req, data)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 496, in _call_chain
        result = func(*args)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

---
2023-08-14 20:52:52,027 - roop - INFO - roop v0.0.2
Downloading the classes list to /home/sd/.ifnude/classes
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1282, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1328, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1277, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1037, in _send_output
        self.send(msg)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 975, in send
        self.connect()
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/http/client.py", line 1454, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/ssl.py", line 513, in wrap_socket
        return self.sslsocket_class._create(
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/ssl.py", line 1071, in _create
        self.do_handshake()
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/ssl.py", line 1342, in do_handshake
        self._sslobj.do_handshake()
    ConnectionResetError: [Errno 104] Connection reset by peer

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/sd/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 14, in <module>
        from scripts.cimage import convert_to_sd
      File "/home/sd/stable-diffusion-webui/extensions/sd-webui-roop/scripts/cimage.py", line 2, in <module>
        from ifnude import detect
      File "/home/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/ifnude/__init__.py", line 1, in <module>
        from .detector import detect
      File "/home/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/ifnude/detector.py", line 40, in <module>
        download(classes_url, classes_path)
      File "/home/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/ifnude/detector.py", line 16, in download
        request = urllib.request.urlopen(url)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 519, in open
        response = self._open(req, data)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 496, in _call_chain
        result = func(*args)
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "/home/sd/anaconda3/envs/sd/lib/python3.10/urllib/request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

**Comment by nyukers** [comment]
Are You using **SD-CN-Animation** ? Turn off him.

**Comment by zhengdong890** [comment]
> Are You using **SD-CN-Animation** ? Turn off him.
No

**Comment by Gourieff** [comment]
@zhengdong890 according to your log - there's smth wrong with the "ifnude" package (NSFW detector), try to reinstall "ifnude" inside your venv
Or you can also try my [fork](https://github.com/Gourieff/sd-webui-reactor) it works without "ifnude"
