### ISSUE TITLE
ComfyUI ROOP installation failed.

### ISSUE THREAD

**Issue by nyukers** [s0md3v/sd-webui-roop#207]
**ComfyUI Portable version Windows 10:**
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iinsightface/thirdparty/face3d/mesh/cython -IC:\SDComfyUI\python_embeded\lib\site-packages\numpy\core\include -IC:\SDComfyUI\python_embeded\include -IC:\SDComfyUI\python_embeded\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpinsightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp /Fobuild\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.obj
      mesh_core_cython.cpp
      insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp(36): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
Command '['C:\\SDComfyUI\\python_embeded\\python.exe', '-m', 'pip', 'install', 'insightface==0.7.3']' returned non-zero exit status 1.
Warning: Failed to install insightface==0.7.3, roop will not work.

**A1111 Portable and ROOP on the same Windows Ok.**

**Comment by nyukers** [comment]
I did complete the installation ROOP as required. But when I started ComfyUI, there was another problem - now ROOP was missing a DLL. I'm not proud, I'll put it where it needs to be, just tell me which one...(((

Traceback (most recent call last):
  File "C:\SDComfyUI\ComfyUI\nodes.py", line 1665, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI_roop\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI_roop\nodes.py", line 3, in <module>
    from scripts.faceswap import FaceSwapScript, get_models
  File "C:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI_roop\scripts\faceswap.py", line 16, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "C:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI_roop\scripts\swapper.py", line 12, in <module>
    import insightface
  File "C:\SDComfyUI\python_embeded\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\SDComfyUI\python_embeded\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\SDComfyUI\python_embeded\lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "C:\SDComfyUI\python_embeded\lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "C:\SDComfyUI\python_embeded\lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: DLL load failed while importing mesh_core_cython: The specified module could not be found.

**Comment by nyukers** [comment]
set appdata=tmp
set userprofile=tmp
set temp=tmp
set path=git\cmd;python;venv\scripts
call venv\scripts\activate.bat
pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
