### ISSUE TITLE
faceswap.py error. 

### ISSUE THREAD

**Issue by ZeFluffyNuphkin** [s0md3v/sd-webui-roop#216]
Every time I try to use this extension I get this error. Nothing is working.

```
*** Error running postprocess_image: F:\Stable_diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "F:\Stable_diffusion\stable-diffusion-webui\modules\scripts.py", line 575, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "F:\Stable_diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
        result: ImageResult = swap_face(
      File "F:\Stable_diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 127, in swap_face
        face_swapper = getFaceSwapModel(model_path)
      File "F:\Stable_diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 40, in getFaceSwapModel
        FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
      File "F:\Stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "F:\Stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "F:\Stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "F:\Stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "F:\Stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from F:\Stable_diffusion\stable-diffusion-webui\models\roop\inswapper_128.onnx failed:Protobuf parsing failed.
```

I have literally no other extensions downloaded, not even built-in extensions. faceswap.py just refuses to work. If anyone could help me that would be greatly appreciated.

**Comment by nyukers** [comment]
Repeat download minswapper_128.onnx manually.
