### ISSUE TITLE
 Error running postprocess_image

### ISSUE THREAD

**Issue by lord-dakon** [s0md3v/sd-webui-roop#218]
Error running postprocess_image: G:\SD 1.5\sd.webui\webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "G:\SD 1.5\sd.webui\webui\modules\scripts.py", line 575, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "G:\SD 1.5\sd.webui\webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
        result: ImageResult = swap_face(
      File "G:\SD 1.5\sd.webui\webui\extensions\sd-webui-roop\scripts\swapper.py", line 123, in swap_face
        source_face = get_face_single(source_img, face_index=0)
      File "G:\SD 1.5\sd.webui\webui\extensions\sd-webui-roop\scripts\swapper.py", line 76, in get_face_single
        face_analyser = insightface.app.FaceAnalysis(name="buffalo_l", providers=providers)
      File "G:\SD 1.5\sd.webui\system\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
        assert 'detection' in self.models
    AssertionError

If anyone could help me that would be greatly appreciated.

**Comment by zszroses** [comment]
I also encountered the same situation as you and I don’t know how to solve it
