### ISSUE TITLE
401 error in swapping face

### ISSUE THREAD

**Issue by heloedward** [s0md3v/sd-webui-roop#219]
Traceback (most recent call last):
  File "/content/roop/run.py", line 6, in <module>
    core.run()
  File "/content/roop/roop/core.py", line 231, in run
    if not frame_processor.pre_check():
  File "/content/roop/roop/processors/frame/face_swapper.py", line 20, in pre_check
    conditional_download(download_directory_path, ['https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx'])
  File "/content/roop/roop/utilities.py", line 134, in conditional_download
    request = urllib.request.urlopen(url) # type: ignore[attr-defined]
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by ashleykleynhans** [comment]
All the inswapper models were removed/made private on Huggingface and are no longer accessible.

**Comment by georgesung** [comment]
Is it removed due to this? https://huggingface.co/deepinsight-unofficial/inswapper/discussions/2
Timeline checks out

**Comment by georgesung** [comment]
Found a workaround:

1. Download `inswapper_128.onnx` from https://drive.google.com/file/d/1krOLgjW2tAPaqV-Bw4YALz0xT5zlb5HF/view
2. Copy `inswapper_128.onnx` to `./models/roop/`

Now `install.py` should find the `inswapper_128.onnx` file and roop can work as expected.

Thanks to [this Github issue comment](https://github.com/deepinsight/insightface/issues/2294#issuecomment-1579968331), which was based on [this Reddit comment](https://www.reddit.com/r/midjourney/comments/13pnraj/comment/jlxsoxz/?utm_source=share&utm_medium=web2x&context=3).

From what I gathered, the insightface owner (creator of inswapper) removed the file from their Github (https://github.com/deepinsight/insightface/issues/2294). It was then re-uploaded to HuggingFace by another user, which roop was pulling from. Then the model on HF was taken down due to https://huggingface.co/deepinsight-unofficial/inswapper/discussions/2
