### ISSUE TITLE
oop_face_swap_english_colab.ipynb doesn't work

### ISSUE THREAD

**Issue by navasgejza** [s0md3v/sd-webui-roop#221]
For about 6 hours I can't use this face swap software.

Here's what it says:

Traceback (most recent call last):
  File "/content/roop/run.py", line 6, in <module>
    core.run()
  File "/content/roop/roop/core.py", line 208, in run
    if not frame_processor.pre_check():
  File "/content/roop/roop/processors/frame/face_swapper.py", line 30, in pre_check
    conditional_download(download_directory_path, ['https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx'])
  File "/content/roop/roop/utilities.py", line 134, in conditional_download
    request = urllib.request.urlopen(url) # type: ignore[attr-defined]
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

Does any one lse expericences this issue?

Thank you, 

Géza.

**Comment by serkanturhanxl** [comment]
inswapper_128.onnx file removed from git.
I have the same issue. I should find the inswapper_128.onnx file

**Comment by navasgejza** [comment]
Hope you can find it. Please sign me if you can solve this problem.  Thanks,  Bests, Géza.

**Comment by serkanturhanxl** [comment]
> Hope you can find it. Please sign me if you can solve this problem. Thanks, Bests, Géza.

Download from here
https://huggingface.co/deepinsight/inswapper/tree/main
and put in models/roop folder.

**Comment by heloedward** [comment]
There are two link is invalid to download the file. The fastest way is to replace it with valid link and upload theface_swapper.py and face_enhancer.py file into roop>roop>processors>frame. You can download those two .py file and change corresponding link by below one

https://huggingface.co/deepinsight/inswapper/resolve/main/inswapper_128.onnx
https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth

> > Hope you can find it. Please sign me if you can solve this problem. Thanks, Bests, Géza.
> 
> Download from here https://huggingface.co/deepinsight/inswapper/tree/main and put in models/roop folder.

**Comment by S3cretLORE** [comment]
Any solution to this?

**Comment by ashleykleynhans** [comment]
> > Hope you can find it. Please sign me if you can solve this problem. Thanks, Bests, Géza.
> 
> Download from here https://huggingface.co/deepinsight/inswapper/tree/main and put in models/roop folder.

This one was also taken down.

**Comment by serkanturhanxl** [comment]
> > > Hope you can find it. Please sign me if you can solve this problem. Thanks, Bests, Géza.
> > 
> > 
> > Download from here https://huggingface.co/deepinsight/inswapper/tree/main and put in models/roop folder.
> 
> This one was also taken down.

Try this

https://drive.google.com/file/d/1krOLgjW2tAPaqV-Bw4YALz0xT5zlb5HF/view?usp=sharing

**Comment by kymaira** [comment]
Change line 12 of install.py to this:
model_url = "https://huggingface.co/ezioruan/inswapper_128.onnx/resolve/main/inswapper_128.onnx"
