### ISSUE TITLE
Insightface not found but already installed.

### ISSUE THREAD

**Issue by dnihil** [s0md3v/sd-webui-roop#222]
Getting this error, but insightface is already installed

2023-08-23 00:01:37,042 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

**Comment by dnihil** [comment]
Seeing this earlier on in the load.

*** Error running install.py for extension E:\stable-diffusion-webui\extensions\sd-webui-roop.
*** Command: "E:\stable-diffusion-webui\venv\Scripts\python.exe" "E:\stable-diffusion-webui\extensions\sd-webui-roop\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "E:\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 25, in <module>
***     download(model_url, model_path)
***   File "E:\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 16, in download
***     request = urllib.request.urlopen(url)
***   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 216, in urlopen
***     return opener.open(url, data, timeout)
***   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 525, in open
***     response = meth(req, response)
***   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 634, in http_response
***     response = self.parent.error(
***   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 563, in error
***     return self._call_chain(*args)
***   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 496, in _call_chain
***     result = func(*args)
***   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 643, in http_error_default
***     raise HTTPError(req.full_url, code, msg, hdrs, fp)
*** urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by lucianoambrosini** [comment]
same here :(

**Comment by Chettawan** [comment]
Got same error on Automatic1111 start up. Visual studio and roop extension install seem fine no error

*** Error running install.py for extension C:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-roop.
*** Command: "C:\Stable-Diffusion\stable-diffusion-webui\venv\Scripts\python.exe" "C:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "C:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 25, in <module>
***     download(model_url, model_path)
***   File "C:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 16, in download
***     request = urllib.request.urlopen(url)
***   File "C:\Users\chett\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
***     return opener.open(url, data, timeout)
***   File "C:\Users\chett\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
***     response = meth(req, response)
***   File "C:\Users\chett\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
***     response = self.parent.error(
***   File "C:\Users\chett\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
***     return self._call_chain(*args)
***   File "C:\Users\chett\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
***     result = func(*args)
***   File "C:\Users\chett\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
***     raise HTTPError(req.full_url, code, msg, hdrs, fp)
*** urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by Chettawan** [comment]
I think there something wrong about hugging face model. It said the access to this resource is disabled.

**Comment by alieverlove** [comment]
@Chettawan Thanks Brother. its works.

**Comment by SgtXQsME** [comment]
@Chettawan hey bro! I downloaded the file. error still not resolved. help me

**Comment by Chettawan** [comment]
> @Chettawan hey bro! I downloaded the file. error still not resolved. help me

Can you post the error message in Automatic1111 startup. May be it's not the same case.

**Comment by SgtXQsME** [comment]
![image](https://github.com/s0md3v/sd-webui-roop/assets/117837592/9dc90b9d-a377-49d5-9cd6-dc4e6242d222)
![image](https://github.com/s0md3v/sd-webui-roop/assets/117837592/262ae25b-76c2-44dd-bdb6-286ebf9b4ba7)
![image](https://github.com/s0md3v/sd-webui-roop/assets/117837592/7e46d9db-6d53-446e-973d-fd856e21bc44)
![image](https://github.com/s0md3v/sd-webui-roop/assets/117837592/cc731dc8-4f41-4602-a538-1edc520f6fd6)
these are the errors I'm facing right now

**Comment by Nayrobie** [comment]
> 

Your solution worked for me! Thanks  a lot :)

**Comment by WaseekSenju** [comment]
> ![image](https://user-images.githubusercontent.com/117837592/263681144-9dc90b9d-a377-49d5-9cd6-dc4e6242d222.png) ![image](https://user-images.githubusercontent.com/117837592/263681219-262ae25b-76c2-44dd-bdb6-286ebf9b4ba7.png) ![image](https://user-images.githubusercontent.com/117837592/263681275-7e46d9db-6d53-446e-973d-fd856e21bc44.png) ![image](https://user-images.githubusercontent.com/117837592/263681573-cc731dc8-4f41-4602-a538-1edc520f6fd6.png) these are the errors I'm facing right now

I am facing the exact same error.

**Comment by WaseekSenju** [comment]
> I think there something wrong about hugging face model. It said the access to this resource is disabled.
> 
> Ok I've managed to fix it. You need to manually download inswapper_128.onx from this URL https://drive.google.com/file/d/1krOLgjW2tAPaqV-Bw4YALz0xT5zlb5HF/view
> 
> and put it to Stable-Diffusion folder\stable-diffusion-webui\models\roop
> 
> Then just start Stable Diffusion again.
> 
> The error gone Checking roop requirements Install insightface==0.7.3 Installing sd-webui-roop requirement: insightface==0.7.3 Install onnx==1.14.0 Installing sd-webui-roop requirement: onnx==1.14.0 Install onnxruntime==1.15.0 Installing sd-webui-roop requirement: onnxruntime==1.15.0 Install opencv-python==4.7.0.72 Installing sd-webui-roop requirement: opencv-python==4.7.0.72 Install ifnude Installing sd-webui-roop requirement: ifnude

Thank you so much it worked!

**Comment by hungle-i3** [comment]
> Seeing this earlier on in the load.
> 
> *** Error running install.py for extension E:\stable-diffusion-webui\extensions\sd-webui-roop. *** Command: "E:\stable-diffusion-webui\venv\Scripts\python.exe" "E:\stable-diffusion-webui\extensions\sd-webui-roop\install.py" *** Error code: 1 *** stderr: Traceback (most recent call last): *** File "E:\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 25, in *** download(model_url, model_path) *** File "E:\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 16, in download *** request = urllib.request.urlopen(url) *** File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 216, in urlopen *** return opener.open(url, data, timeout) *** File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 525, in open *** response = meth(req, response) *** File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 634, in http_response *** response = self.parent.error( *** File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 563, in error *** return self._call_chain(*args) *** File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 496, in _call_chain *** result = func(*args) *** File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 643, in http_error_default *** raise HTTPError(req.full_url, code, msg, hdrs, fp) *** urllib.error.HTTPError: HTTP Error 401: Unauthorized

The model url from huggingface was closed to be accessed from public so download command got HTTP 401 (Unauthorized).

There are 2 ways to resolve the problem.
1. Login huggingface to download and install manually
2. Modify install.py script \stable-diffusion-webui\extensions\sd-webui-roop\install.py to download an alternative.
#model_url = "https://huggingface.co/deepinsight/inswapper/resolve/main/inswapper_128.onnx"
model_url = "https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx"

**Comment by alaowu** [comment]
@SgtXQsME hi Have you solved this problem? And how was it resolved? I have the same problem

C:\Users\Administrator>pip show insightface
Name: insightface
Version: 0.7.3
Summary: InsightFace Python Library
Home-page: https://github.com/deepinsight/insightface
Author: InsightFace Contributors
Author-email: contact@insightface.ai
License: MIT
Location: C:\Python312\Lib\site-packages
Requires: albumentations, cython, easydict, matplotlib, numpy, onnx, Pillow, prettytable, requests, scikit-image, scikit-learn, scipy, tqdm
Required-by:

*** Error loading script: api.py
    Traceback (most recent call last):
      File "E:\StableDiffusion\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\StableDiffusion\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\StableDiffusion\extensions\sd-webui-roop\scripts\api.py", line 17, in <module>
        from scripts.faceswap import get_models
      File "E:\StableDiffusion\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "E:\StableDiffusion\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---

**Comment by SgtXQsME** [comment]
@alaowu Hello brother!
Yeah I solved this issue.First of all you unintall the all python versions and reinstall the python 3.10 version. After that delete old copies of your stable diffusion and try to reinstall the Stable diffusion as a new copy. This method solved my problem.

**Comment by alaowu** [comment]
@SgtXQsME Thank you very much！I solved this problem.
