### ISSUE TITLE
Error installing roop

### ISSUE THREAD

**Issue by wicherek1** [s0md3v/sd-webui-roop#227]
Hello
I have a problem with installing roop extention. I did everything as in the manual including installing VS 2022 with Python and C++ packages and running command: pip install insightface==0.7.3. But after that when I try to install the extention on A1111 an error occurs:

*** Error running install.py for extension C:\AI\stable-diffusion-webui\extensions\sd-webui-roop.
*** Command: "C:\AI\stable-diffusion-webui\venv\Scripts\python.exe" "C:\AI\stable-diffusion-webui\extensions\sd-webui-roop\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "C:\AI\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 25, in <module>
***     download(model_url, model_path)
***   File "C:\AI\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 16, in download
***     request = urllib.request.urlopen(url)
***   File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
***     return opener.open(url, data, timeout)
***   File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
***     response = meth(req, response)
***   File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
***     response = self.parent.error(
***   File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
***     return self._call_chain(*args)
***   File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
***     result = func(*args)
***   File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
***     raise HTTPError(req.full_url, code, msg, hdrs, fp)
*** urllib.error.HTTPError: HTTP Error 401: Unauthorized

And after a while:

*** Error loading script: api.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\api.py", line 17, in <module>
        from scripts.faceswap import get_models
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

---
*** Error loading script: cimage.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

---
2023-08-27 13:47:55,766 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

I have installed the "onruxruntime" and "ifnude" manually but it didn't work.
In the extensions tab I have a roop "installed" but it does not appear in the Script tab.

I don't know if it matters but before doing everything right as in the manual I installed roop in the extension tab without VS 2022 with packages.

**Comment by ZeroCool22** [comment]
The Dev got too "moral" and discontinued this project, here you have an alternative:

https://github.com/Gourieff/sd-webui-reactor

**Comment by vfx999** [comment]
@wicherek1  I had exactly the same issue, Have you figured it out?

**Comment by RazaGR** [comment]
just change the url in install.py file to
```
model_url = "https://huggingface.co/facefusion/models/resolve/main/inswapper_128.onnx"
```

**Comment by vfx999** [comment]
@RazaGR 
**It worked. Thank you very much.** 

But there was another problem. It doesn't process faceswap. I tried it with txt2img & img2img and it didn't work at all. I tried upgrading the Web UI, and an extension and even checked the file located at C:\Users\Administrator.insightface\models\buffalo_l.  still no luck

It gave me this:

Error running postprocess_image: G:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "G:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 575, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "G:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
        result: ImageResult = swap_face(
      File "G:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 127, in swap_face
        face_swapper = getFaceSwapModel(model_path)
      File "G:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 40, in getFaceSwapModel
        FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
      File "G:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "G:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "G:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "G:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "G:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from G:\Stable Diffusion\stable-diffusion-webui\models\roop\inswapper_128.onnx failed:Protobuf parsing failed.

**Comment by nyukers** [comment]
Repeat download minswapper_128.onnx manually.

**Comment by w-walber** [comment]
Here is the solution i found, it work for me:
1- Windows+CMD
2 - type the commands:
pip install onnxruntime-gpu
pip install onnxruntime
pip install ifnude --upgrade

3 - go to your Cstable-diffusion-webui\venv\Scripts folcer, and type CMD in the search bar
4 - type the commands:
pip install onnxruntime-gpu
pip install onnxruntime
pip install ifnude --upgrade

**Comment by xumijiezi622** [comment]
Problem solved, thank you~

**Comment by davioni** [comment]
error with No module named 'ifnude' 
done 
press anykey to continue, immediately i press any key the whole command closes 
need help please
