### ISSUE TITLE
Error by loading the extension

### ISSUE THREAD

**Issue by KRIShark** [s0md3v/sd-webui-roop#237]
*** Error loading script: api.py
    Traceback (most recent call last):
      File "K:\ImageAI\AI\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "K:\ImageAI\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "K:\ImageAI\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\api.py", line 17, in <module>
        from scripts.faceswap import get_models
      File "K:\ImageAI\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "K:\ImageAI\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: cimage.py
    Traceback (most recent call last):
      File "K:\ImageAI\AI\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "K:\ImageAI\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "K:\ImageAI\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "K:\ImageAI\AI\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "K:\ImageAI\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "K:\ImageAI\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "K:\ImageAI\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
2023-09-08 02:02:25,145 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "K:\ImageAI\AI\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "K:\ImageAI\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "K:\ImageAI\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

**Comment by navin-hariharan** [comment]
#240 View this!
