### ISSUE TITLE
 AttributeError

### ISSUE THREAD

**Issue by handsowex** [s0md3v/sd-webui-roop#239]
*** Error running process: E:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py2<00:00,  8.51it/s]
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
    TypeError: FaceSwapScript.process() missing 11 required positional arguments: 'img', 'enable', 'faces_index', 'model', 'face_restorer_name', 'face_restorer_visibility', 'upscaler_name', 'upscaler_scale', 'upscaler_visibility', 'swap_in_source', and 'swap_in_generated'

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.80it/s]
*** Error running postprocess_batch: E:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py8.54it/s]
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\scripts.py", line 659, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 177, in postprocess_batch
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: E:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

**Comment by handsowex** [comment]
Is there anyone who can help?

**Comment by handsowex** [comment]
Is there anyone who can help?

**Comment by Gourieff** [comment]
Try this solution https://github.com/Gourieff/sd-webui-reactor#iv-attributeerror-faceswapscript-object-has-no-attribute-enable
