### ISSUE TITLE
NameError: name 'urllib' is not defined

### ISSUE THREAD

**Issue by swumagic** [s0md3v/sd-webui-roop#24]
Error loading script: cimage.py
Traceback (most recent call last):
  File "M:\SD\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\SD\sdwebui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\__init__.py", line 1, in <module>
    from .detector import detect
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 35, in <module>
    download(model_url, model_path)
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 15, in download
    request = urllib.request.urlopen(url)
NameError: name 'urllib' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Downloading the detection model to C:\Users\dckf\.models/detector.onnx
Error loading script: faceswap.py
Traceback (most recent call last):
  File "M:\SD\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\SD\sdwebui\extensions\sd-webui-roop\scripts\faceswap.py", line 15, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "M:\SD\sdwebui\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
    from scripts.cimage import convert_to_sd
  File "M:\SD\sdwebui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\__init__.py", line 1, in <module>
    from .detector import detect
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 35, in <module>
    download(model_url, model_path)
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 15, in download
    request = urllib.request.urlopen(url)
NameError: name 'urllib' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

2023-06-20 23:36:04,537 - roop - INFO - roop v0.0.2
Downloading the detection model to C:\Users\dckf\.models/detector.onnx
Error loading script: swapper.py
Traceback (most recent call last):
  File "M:\SD\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\SD\sdwebui\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
    from scripts.cimage import convert_to_sd
  File "M:\SD\sdwebui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\__init__.py", line 1, in <module>
    from .detector import detect
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 35, in <module>
    download(model_url, model_path)
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 15, in download
    request = urllib.request.urlopen(url)
NameError: name 'urllib' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by s0md3v** [comment]
You are using an old version of this software.

**Comment by swumagic** [comment]
I have been updating to the latest version, but it keeps prompting an error. Only the version on June 18 can run normally
