### ISSUE TITLE
ERROR , automic 1111  latest update

### ISSUE THREAD

**Issue by EKI-INDRADI** [s0md3v/sd-webui-roop#240]
visual C++ desktop + python   already installed (visual studio)

*** Error loading script: api.py
    Traceback (most recent call last):
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\api.py", line 17, in <module>
        from scripts.faceswap import get_models
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

---
*** Error loading script: cimage.py
    Traceback (most recent call last):
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

---
2023-09-09 22:13:33,720 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "V:\STABLE_DIFFUSION\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

---

**Comment by navin-hariharan** [comment]
@EKI-INDRADI Downlaod the model!

Get https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx

Put it in models/roop/inswapper_128.onnx

**Comment by EKI-INDRADI** [comment]
solved im using guide & step ReActor

**Comment by Moiz439** [comment]
i install the roop but not visible in my webui how can solve this?
<img width="960" alt="roop" src="https://github.com/s0md3v/sd-webui-roop/assets/71594607/b96a4005-0c87-473c-9cb9-14857ffb98d2">

**Comment by navin-hariharan** [comment]
> i install the roop but not visible in my webui how can solve this? <img alt="roop" width="960" src="https://private-user-images.githubusercontent.com/71594607/287424232-b96a4005-0c87-473c-9cb9-14857ffb98d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0OTg0NTcsIm5iZiI6MTcwMTQ5ODE1NywicGF0aCI6Ii83MTU5NDYwNy8yODc0MjQyMzItYjk2YTQwMDUtMGM4Ny00NzNjLTljYjktMTQ4NTdmZmI5OGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDA2MjIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YzQ5NWU0YmRiMDIxY2ZiMDcwNWMwNTBkN2JhZTZiZDA5YTBiNjYxZjkzMmQwMmM5YWE4MzdjMDI2ODI2NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ue57VnTTZtkq91LMqd4esAhhfHR8HNeoMCeU4BV0_HY">

Can I see your extensions tab and console?

I'll recommend uninstalling roop and installing [FACE REACTOR](https://www.youtube.com/watch?v=Da6J3wjBx3A&t)

**Comment by biletian** [comment]
Do you know if there is any god who installs a good reactor but after generating it, there is no effect of changing faces?
