### ISSUE TITLE
RuntimeError: storage has wrong byte size: expected %ld got %ld01048576

### ISSUE THREAD

**Issue by yuan-0708** [s0md3v/sd-webui-roop#243]
webuidocker-test-autotest-1  | *** Error running postprocess_image: /stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
webuidocker-test-autotest-1  |     Traceback (most recent call last):
webuidocker-test-autotest-1  |       File "/stable-diffusion-webui/modules/scripts.py", line 575, in postprocess_image
webuidocker-test-autotest-1  |         script.postprocess_image(p, pp, *script_args)
webuidocker-test-autotest-1  |       File "/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 184, in postprocess_image
webuidocker-test-autotest-1  |         result: ImageResult = swap_face(
webuidocker-test-autotest-1  |       File "/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 138, in swap_face
webuidocker-test-autotest-1  |         result_image = upscale_image(result_image, upscale_options)
webuidocker-test-autotest-1  |       File "/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 66, in upscale_image
webuidocker-test-autotest-1  |         numpy_image = upscale_options.face_restorer.restore(numpy_image)
webuidocker-test-autotest-1  |       File "/stable-diffusion-webui/modules/gfpgan_model.py", line 106, in restore
webuidocker-test-autotest-1  |         return gfpgan_fix_faces(np_image)
webuidocker-test-autotest-1  |       File "/stable-diffusion-webui/modules/gfpgan_model.py", line 51, in gfpgan_fix_faces
webuidocker-test-autotest-1  |         model = gfpgann()
webuidocker-test-autotest-1  |       File "/stable-diffusion-webui/modules/gfpgan_model.py", line 38, in gfpgann
webuidocker-test-autotest-1  |         model = gfpgan_constructor(model_path=model_file, upscale=1, arch='clean', channel_multiplier=2, bg_upsampler=None, device=devices.device_gfpgan)
webuidocker-test-autotest-1  |       File "/usr/local/lib/python3.10/site-packages/gfpgan/utils.py", line 92, in __init__
webuidocker-test-autotest-1  |         loadnet = torch.load(model_path)
webuidocker-test-autotest-1  |       File "/stable-diffusion-webui/modules/safe.py", line 108, in load
webuidocker-test-autotest-1  |         return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
webuidocker-test-autotest-1  |       File "/stable-diffusion-webui/modules/safe.py", line 156, in load_with_extra
webuidocker-test-autotest-1  |         return unsafe_torch_load(filename, *args, **kwargs)
webuidocker-test-autotest-1  |       File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
webuidocker-test-autotest-1  |         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
webuidocker-test-autotest-1  |       File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 1051, in _legacy_load
webuidocker-test-autotest-1  |         typed_storage._untyped_storage._set_from_file(
webuidocker-test-autotest-1  |     RuntimeError: storage has wrong byte size: expected %ld got %ld01048576

使用roop插件出图，报以上错误，麻烦各位大佬帮忙看看，谢谢

**Comment by YouXMu** [comment]
你好，这个问题解决了吗？我也遇到类似的问题了，请问是怎么解决的呢
