### ISSUE TITLE
I cannot see the roop extention UI and nothing seems to work please help

### ISSUE THREAD

**Issue by Kardino** [s0md3v/sd-webui-roop#245]
Hi, I have been trying to get roop work but no solution I find online seems to work I keep getting errors. I cannot see the roop extension UI in stable diffusion and I have already uninstalled and redownloaded stable diffusion once in hopes of getting it to work, if anyone can help me I will be glad. 

`Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop.
*** Command: "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\venv\Scripts\python.exe" "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 25, in <module>
***     download(model_url, model_path)
***   File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 16, in download
***     request = urllib.request.urlopen(url)
***   File "C:\Users\edide\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
***     return opener.open(url, data, timeout)
***   File "C:\Users\edide\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
***     response = meth(req, response)
***   File "C:\Users\edide\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
***     response = self.parent.error(
***   File "C:\Users\edide\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
***     return self._call_chain(*args)
***   File "C:\Users\edide\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
***     result = func(*args)
***   File "C:\Users\edide\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
***     raise HTTPError(req.full_url, code, msg, hdrs, fp)
*** urllib.error.HTTPError: HTTP Error 401: Unauthorized
Launching Web UI with arguments:
[-] ADetailer initialized. version: 23.9.2, num models: 9
2023-09-12 20:22:23,893 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-12 20:22:23,975 - ControlNet - INFO - ControlNet v1.1.410
*** Error loading script: api.py
    Traceback (most recent call last):
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\api.py", line 17, in <module>
        from scripts.faceswap import get_models
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: cimage.py
    Traceback (most recent call last):
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
2023-09-12 20:22:23,987 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
Loading weights [6ce0161689] from C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\configs\v1-inference.yaml
C:\Users\edide\OneDrive\Masaüstü\AI\AI Folder\Stable Diffusion\stable-diffusion-webui\extensions\next-diffusion-prompt-generator\scripts\prompt_generator.py:167: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=True):  # Place dropdowns side by side`

**Comment by Autantpourmoi** [comment]
same to me , i tried wit 'pip install insightface==0.7.3' and reinstall extension it doesn't work

**Comment by mmazurkevich** [comment]
@Autantpourmoi  @Kardino 
Here is an answer https://github.com/s0md3v/sd-webui-roop/issues/240#issuecomment-1712650799
The root cause described here https://github.com/s0md3v/sd-webui-roop/issues/227#issuecomment-1699098645

**Comment by iammikomaestro** [comment]
I encountered the same error and im lost already. I have downloaded the solution #240 but still the same error. HELP PLEASE!

**Comment by Vetrov0x** [comment]
Same, #240 and #227 didn't solve the problem

**Comment by Moiz439** [comment]
in webui roop option is not visible plz give some solutions.

<img width="960" alt="roop" src="https://github.com/s0md3v/sd-webui-roop/assets/71594607/42532711-3816-4e27-aadf-d8270f109343">
