### ISSUE TITLE
When I use roop in the api, after the first graph, subsequent calls will get an error

### ISSUE THREAD

**Issue by HtopH** [s0md3v/sd-webui-roop#246]
*** API error: POST: http://127.0.0.1:200/sdapi/v1/txt2img {'error': 'TypeError', 'detail': '', 'body': '', 'errors': 'expected string or bytes-like object'}
    Traceback (most recent call last):
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/anyio/streams/memory.py", line 98, in receive
        return self.receive_nowait()
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/admin/Data/code/python/stable-diffusion-webui/modules/api/api.py", line 187, in exception_handling
        return await call_next(request)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "/home/admin/Data/code/python/stable-diffusion-webui/modules/api/api.py", line 151, in log_and_time
        res: Response = await call_next(req)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 26, in __call__
        await self.app(scope, receive, send)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
        raise exc
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
        raise e
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
        response = await func(request)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "/home/admin/Data/code/python/stable-diffusion-webui/modules/api/api.py", line 380, in text2imgapi
        processed = process_images(p)
      File "/home/admin/Data/code/python/stable-diffusion-webui/modules/processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "/home/admin/Data/code/python/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/home/admin/Data/code/python/stable-diffusion-webui/modules/processing.py", line 838, in process_images_inner
        p.parse_extra_network_prompts()
      File "/home/admin/Data/code/python/stable-diffusion-webui/modules/processing.py", line 1334, in parse_extra_network_prompts
        res = super().parse_extra_network_prompts()
      File "/home/admin/Data/code/python/stable-diffusion-webui/modules/processing.py", line 476, in parse_extra_network_prompts
        self.prompts, self.extra_network_data = extra_networks.parse_prompts(self.prompts)
      File "/home/admin/Data/code/python/stable-diffusion-webui/modules/extra_networks.py", line 199, in parse_prompts
        updated_prompt, parsed_extra_data = parse_prompt(prompt)
      File "/home/admin/Data/code/python/stable-diffusion-webui/modules/extra_networks.py", line 189, in parse_prompt
        prompt = re.sub(re_extra_net, found, prompt)
      File "/home/admin/anaconda3/envs/sd-webui/lib/python3.10/re.py", line 209, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object

**Comment by HtopH** [comment]
The arguments I call roop are:
param["alwayson_scripts"] = map[string]interface{}{
		"roop": map[string]interface{}{
			"args": []interface{}{
				img,
				true,
				"0",
				"/home/admin/Data/code/python/stable-diffusion-webui-master/models/roop/inswapper_128.onnx",
				"CodeFormer",
				1,
				"R-ESRGAN 4x+",
				1,
				1,
				false,
				true,
			},
		},
	}

**Comment by Gourieff** [comment]
Your `img` variable - what is it?
A source image as it is?

**Comment by Gourieff** [comment]
If `img` is a path to a source image, then you have to do smth like that:
```python
import base64, io
from PIL import Image

img = "/home/admin/images/face_image.jpg" # path to your source image

source_image = Image.open(img)
image_bytes = io.BytesIO()
source_image.save(image_bytes, format='PNG')
image_base64 = base64.b64encode(image_bytes.getvalue()).decode('utf-8')
```
`image_base64` - is the object you need to send instead of `img`

**Comment by HtopH** [comment]
> If `img` is a path to a source image, then you have to do smth like that:
> 
> ```python
> import base64, io
> from PIL import Image
> 
> img = "/home/admin/images/face_image.jpg" # path to your source image
> 
> source_image = Image.open(img)
> image_bytes = io.BytesIO()
> source_image.save(image_bytes, format='PNG')
> image_base64 = base64.b64encode(image_bytes.getvalue()).decode('utf-8')
> ```
> 
> `image_base64` - is the object you need to send instead of `img`

Yes, img here is a string variable, I have converted the image to base64, I generated this error through the api call, but very miraculously, as soon as I generate an image in the web page operation, the error will not appear again, I guess I used the api to call roop, some configuration was not initialized
