### ISSUE TITLE
what's the matter?

### ISSUE THREAD

**Issue by g558800** [s0md3v/sd-webui-roop#25]
venv "H:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.3.2-RC-1-gbaf6946e
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing requirements

Error running install.py for extension H:\AI\stable-diffusion-webui\extensions\sd-webui-roop.
Command: "H:\AI\stable-diffusion-webui\venv\Scripts\python.exe" "H:\AI\stable-diffusion-webui\extensions\sd-webui-roop\install.py"
Error code: 1
stderr: Traceback (most recent call last):
  File "D:\python\Python31011\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\python\Python31011\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\python\Python31011\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\python\Python31011\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\python\Python31011\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "D:\python\Python31011\lib\http\client.py", line 976, in send
    self.connect()
  File "D:\python\Python31011\lib\http\client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "D:\python\Python31011\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\python\Python31011\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\python\Python31011\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] Զǿȹرһеӡ

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\AI\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 25, in <module>
    download(model_url, model_path)
  File "H:\AI\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 16, in download
    request = urllib.request.urlopen(url)
  File "D:\python\Python31011\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\python\Python31011\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\python\Python31011\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\python\Python31011\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\python\Python31011\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\python\Python31011\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] Զǿȹرһеӡ>

Is there an error in executing install.py? Everything that should have been downloaded has already been downloaded.

**Comment by g558800** [comment]
The problem has been solved. It turned out that I placed the model in the roop extension, which is correct for placing it in the stable differentiation webui\models\roop.
