### ISSUE TITLE
the extentionis is installed but it is not visible in the UI

### ISSUE THREAD

**Issue by chouaibmeramria** [s0md3v/sd-webui-roop#252]
i installed the extension but its not showing in the Web UI 
using stable diffusion  
windows 11 *64 

`
```python
---
2023-09-18 05:59:30,563 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "D:\AI\A1111 Webui Launcher V1.7.0\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\A1111 Webui Launcher V1.7.0\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\A1111 Webui Launcher V1.7.0\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'
``` `

**Comment by chouaibmeramria** [comment]
> pip install insightface==0.7.3
> 
> I used an anaconda window to type the command. Once it has installed restart WebUIAuto1111 entirely. Should see that Roop is now installing requirements
> 
> Checking roop requirements Install insightface==0.7.3 Installing sd-webui-roop requirement: insightface==0.7.3 Install onnx==1.14.0 Installing sd-webui-roop requirement: onnx==1.14.0 Install onnxruntime==1.15.0 Installing sd-webui-roop requirement: onnxruntime==1.15.0 Install opencv-python==4.7.0.72 Installing sd-webui-roop requirement: opencv-python==4.7.0.72 Install ifnude Installing sd-webui-roop requirement: ifnude
> 
> If you don't see the reequipments install, then you won't see Roop in the webUI. I just went through this process

tanke you for the answer but i already did that i installed all the requirements and installed Python and C++ packages. but still get the same error . do you have any other suggestion and please which python version do you have

**Comment by ace2duce** [comment]
Not sure, i only installed insightface and then when I restarted the webui, Roop automatically installed the rest

**Comment by ace2duce** [comment]
this alt is good as well, try a fork of the roop webui

https://github.com/Gourieff/sd-webui-reactor

**Comment by distoff11** [comment]
same problem: roop is installed but not visible in ui. please give solution for this

**Comment by chouaibmeramria** [comment]
i installed all these :

protobuf>=3.20.2
insightface==0.7.3
onnx>=1.14.0
onnxruntime>=1.15.0
onnxruntime-gpu>=1.15.0
opencv-python
safetensors
cython
ifnude
opencv-python
pandas
pydantic
safetensors

some how it worked 
try it 

> same problem: roop is installed but not visible in ui. please give solution for this

**Comment by distoff11** [comment]
> i installed all these :
> 
> protobuf>=3.20.2 insightface==0.7.3 onnx>=1.14.0 onnxruntime>=1.15.0 onnxruntime-gpu>=1.15.0 opencv-python safetensors cython ifnude opencv-python pandas pydantic safetensors
> 
> some how it worked try it
> 
> > same problem: roop is installed but not visible in ui. please give solution for this

where should i install all of that (sorry, actually i am a beginner). And i have cpu only to generate images (my gpu is not so powerful) so can i use cpu only in roop ?.  Thank you very much for responding.

**Comment by tkkclym** [comment]
In the same case, it was okay to use it a few days ago, but today I can't use it again

**Comment by qq466627701** [comment]
You need to roll back a program starting with "a"from 4.4 to 4.3,I forgot the full name of that program.

**Comment by qq466627701** [comment]
> You need to roll back a program starting with "a"from 4.4 to 4.3,I forgot the full name of that program.

okay, i have found it.here is the path :"{lorapath}\.ext\Lib\site-packages\albumentations" you need roll back to 1.4.3
