### ISSUE TITLE
Error loading script

### ISSUE THREAD

**Issue by distoff11** [s0md3v/sd-webui-roop#256]
2023-09-21 12:02:35,721 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "C:\Users\Aorus\a1111\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Aorus\a1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Aorus\a1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
        from scripts.cimage import convert_to_sd
      File "C:\Users\Aorus\a1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

**Comment by justarmadillo** [comment]
go to : stable-diffusion-webui\venv\Lib\site-packages

and add these 2 folders from this zip file there it should work
[ifnude.zip](https://github.com/s0md3v/sd-webui-roop/files/12769903/ifnude.zip)

**Comment by Alexandr1968** [comment]
> перейдите по адресу: стабильная-диффузия-webui\venv\Lib\site-packages
> 
> и добавьте туда эти 2 папки из этого zip-файла, должно работать [ifnude.zip](https://github.com/s0md3v/sd-webui-roop/files/12769903/ifnude.zip)

I tried different ways. But it was your option that helped. Thank you very much. Everything is simply ingenious!!!

**Comment by VioletBeauty** [comment]
> 2023-09-21 12:02:35,721 - roop - INFO - roop v0.0.2 *** Error loading script: swapper.py Traceback (most recent call last): File "C:\Users\Aorus\a1111\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "C:\Users\Aorus\a1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\Aorus\a1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 14, in from scripts.cimage import convert_to_sd File "C:\Users\Aorus\a1111\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in from ifnude import detect ModuleNotFoundError: No module named 'ifnude'

I know this thread is a bit old but is there anyway you can point me to a new download. I just tried to download it and doesn't allow me to open or extract from the file.

**Comment by VioletBeauty** [comment]
> go to : stable-diffusion-webui\venv\Lib\site-packages
> 
> and add these 2 folders from this zip file there it should work [ifnude.zip](https://github.com/s0md3v/sd-webui-roop/files/12769903/ifnude.zip)

Hey I know that this was posted back in September of last year but do you have the two folders that were used in this comment by any chance I am running into an issue with the roop extension for stable diffusion and nothing else is working in terms of fixes and this is the only fix I had seen helped others that I haven't tried.
