### ISSUE TITLE
Can't Install on Vast AI remote GPU

### ISSUE THREAD

**Issue by zhao-binxiang** [s0md3v/sd-webui-roop#265]
When I follow the steps, but still getting the following. Plz help.

`*** Error running install.py for extension /workspace/stable-diffusion-webui/extensions/sd-webui-roop.
*** Command: "/workspace/venv/bin/python" "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/install.py", line 25, in <module>
***     download(model_url, model_path)
***   File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/install.py", line 16, in download
***     request = urllib.request.urlopen(url)
***   File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
***     return opener.open(url, data, timeout)
***   File "/usr/lib/python3.10/urllib/request.py", line 525, in open
***     response = meth(req, response)
***   File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
***     response = self.parent.error(
***   File "/usr/lib/python3.10/urllib/request.py", line 563, in error
***     return self._call_chain(*args)
***   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
***     result = func(*args)
***   File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
***     raise HTTPError(req.full_url, code, msg, hdrs, fp)
*** urllib.error.HTTPError: HTTP Error 401: Unauthorized`

`*** Error running install.py for extension /workspace/stable-diffusion-webui/extensions/sd-webui-roop.
*** Command: "/workspace/venv/bin/python" "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/install.py", line 25, in <module>
***     download(model_url, model_path)
***   File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/install.py", line 16, in download
***     request = urllib.request.urlopen(url)
***   File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
***     return opener.open(url, data, timeout)
***   File "/usr/lib/python3.10/urllib/request.py", line 525, in open
***     response = meth(req, response)
***   File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
***     response = self.parent.error(
***   File "/usr/lib/python3.10/urllib/request.py", line 563, in error
***     return self._call_chain(*args)
***   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
***     result = func(*args)
***   File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
***     raise HTTPError(req.full_url, code, msg, hdrs, fp)
*** urllib.error.HTTPError: HTTP Error 401: Unauthorized
Launching Web UI with arguments: --share --api --opt-sdp-attention --listen --enable-insecure-extension-access
No module 'xformers'. Proceeding without it.
[-] ADetailer initialized. version: 23.9.3, num models: 9
Warning: ControlNet failed to load SGM - will use LDM instead.
2023-10-05 08:20:56,762 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: /workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-10-05 08:20:56,871 - ControlNet - INFO - ControlNet v1.1.410
Warning: ControlNet failed to load SGM - will use LDM instead.
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/workspace/venv/lib/python3.10/site-packages/insightface/__init__.py", line 8, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/api.py", line 17, in <module>
        from scripts.faceswap import get_models
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 12, in <module>
        import insightface
      File "/workspace/venv/lib/python3.10/site-packages/insightface/__init__.py", line 10, in <module>
        raise ImportError(
    ImportError: Unable to import dependency onnxruntime. 

---
*** Error loading script: cimage.py
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "/workspace/venv/lib/python3.10/site-packages/insightface/__init__.py", line 8, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 12, in <module>
        import insightface
      File "/workspace/venv/lib/python3.10/site-packages/insightface/__init__.py", line 10, in <module>
        raise ImportError(
    ImportError: Unable to import dependency onnxruntime. 

---
2023-10-05 08:20:56,880 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "/workspace/venv/lib/python3.10/site-packages/insightface/__init__.py", line 8, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 12, in <module>
        import insightface
      File "/workspace/venv/lib/python3.10/site-packages/insightface/__init__.py", line 10, in <module>
        raise ImportError(
    ImportError: Unable to import dependency onnxruntime. 

---`

**Comment by zhao-binxiang** [comment]
Never. downloaded the onnx file and it solved it.
