### ISSUE TITLE
I've followed the installation instructions exactly and it the UI isn't showing.

### ISSUE THREAD

**Issue by Koris95** [s0md3v/sd-webui-roop#272]
The roop UI isn't showing, the extensions tab however says that it is installed. While booting up Stable Diffusion, I get this error before it loads up.
```
Launching Web UI with arguments:
*** Error loading script: api.py
    Traceback (most recent call last):
      File "D:\Stable Diffusion\sd.webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Stable Diffusion\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Stable Diffusion\sd.webui\webui\extensions\sd-webui-roop\scripts\api.py", line 17, in <module>
        from scripts.faceswap import get_models
      File "D:\Stable Diffusion\sd.webui\webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "D:\Stable Diffusion\sd.webui\webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: cimage.py
    Traceback (most recent call last):
      File "D:\Stable Diffusion\sd.webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Stable Diffusion\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Stable Diffusion\sd.webui\webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "D:\Stable Diffusion\sd.webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Stable Diffusion\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Stable Diffusion\sd.webui\webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "D:\Stable Diffusion\sd.webui\webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
2023-10-17 21:27:44,641 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "D:\Stable Diffusion\sd.webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Stable Diffusion\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Stable Diffusion\sd.webui\webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'
```

**Comment by therealMRBK** [comment]
same for me, any fix?

**Comment by GRAYHUI512** [comment]
我的是显示*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "F:\SD\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\SD\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "F:\SD\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'
怎么解决哟

**Comment by izelle** [comment]
Install Visual Studio：Python C++
