### ISSUE TITLE
Error running postprocess_image

### ISSUE THREAD

**Issue by nurullahozatak** [s0md3v/sd-webui-roop#274]
I have this issue. I tried to reinstall sd and the extansion

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.27it/s]
15:33:53 - ReActor - STATUS - Working: source face index [0], target face index [0]████| 20/20 [00:06<00:00,  2.96it/s]
15:33:53 - ReActor - STATUS - Analyzing Source Image...
15:33:57 - ReActor - STATUS - Analyzing Target Image...
15:33:59 - ReActor - STATUS - Detecting Source Face, Index = 0
15:33:59 - ReActor - STATUS - Detected: -21- y.o. Female
*** Error running postprocess_image: E:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 376, in postprocess_image
        result, output, swapped = swap_face(
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 323, in swap_face
        face_swapper = getFaceSwapModel(model)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 92, in getFaceSwapModel
        FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
      File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 21, in patched_get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from E:\AI\stable-diffusion-webui\models\insightface\inswapper_128.onnx failed:Protobuf parsing failed.

---

**Comment by jil49300** [comment]
here is the problem i get : "Error running postprocess_image"

**Comment by zszroses** [comment]
I also encountered the same situation as you and I don’t know how to solve it
