### ISSUE TITLE
Reactor Extension error

### ISSUE THREAD

**Issue by skhoury70** [s0md3v/sd-webui-roop#278]
Can somebody help me to solve the below error? I tried all the steps of the installation and everything looks fine, but when I start, then I got this meesage.
Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion1111\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable Diffusion1111\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable Diffusion1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface

**Comment by Gourieff** [comment]
@skhoury70 https://github.com/Gourieff/sd-webui-reactor#insightfacebuild
