### ISSUE TITLE
can somebody help?

### ISSUE THREAD

**Issue by marcowulur** [s0md3v/sd-webui-roop#29]
Error running postprocess_batch: G:\SD\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py0,  4.14it/s]
Traceback (most recent call last):
  File "G:\SD\stable-diffusion-webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "G:\SD\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 187, in postprocess_image
    result: ImageResult = swap_face(
  File "G:\SD\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 111, in swap_face
    converted = convert_to_sd(target_img)
  File "G:\SD\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 6, in convert_to_sd
    chunks = detect(img)
  File "G:\SD\stable-diffusion-webui\venv\lib\site-packages\ifnude\detector.py", line 46, in detect
    detection_model = onnxruntime.InferenceSession(model_path, providers=["CPUExecutionProvider"])
  File "G:\SD\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "G:\SD\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\LTC\.ifnude/detector.onnx failed:Protobuf parsing failed.

**Comment by gokuchiku** [comment]
I also have a similar issue
![roop final error](https://github.com/s0md3v/sd-webui-roop/assets/136511176/7ab16c34-8e7b-4c9f-b691-2f74afad90c5)

**Comment by xueqing0622** [comment]
same problem,

**Comment by Forevercyj** [comment]
same error

**Comment by gokuchiku** [comment]
> same error

download the onnx file from the updated readme file and do as it says in there

**Comment by klossm** [comment]
still same error
download the [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx) model and put it inside <webui_dir>/models/roop/ directory.

**Comment by klossm** [comment]
I found that it was caused by an error in the process of downloading the model.
Make sure there are these models under the two paths below. If you don't have these folders, you can first create related folders according to the path below.

1. C:\ Users\ directory where the user resides\ .ifnude.

There are detector.onnx and classes models under this path, and the model of detector.onnx is about 139mb. If the model under this path is not the right size, please delete the model in the directory, restart SD and download it again.

2. C:\ Users\ directory where the user resides\ .insightface\ models\ buffalo_l.

There are five models in the buffalo_l folder directory. You can download them from the link below and extract them to the buffalo_l directory.

Https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip

**Comment by xueqing0622** [comment]
I redownload the https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx to the error path:
C:\Users\Admin\.ifnude/detector.onnx(find yours in command.exe)
This is where you block the location needed to download the file, the rest can be downloaded according to the command line prompts if the download is slow

**Comment by wakakmomo** [comment]
Thanks, it works!!! the file "detector.onnx" in folder ".ifnude" is about 138MB, replace it by https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx (139MB!!).

**Comment by lindiny** [comment]
> 我发现是下载模型过程中出现错误导致的。 确保下面三个路径下有这些模型。如果没有这些文件夹，可以先按照下面的路径创建相关文件夹。
> 
> 1. C:\Users\用户所在目录\.ifnude
> 
> 该路径下有Detector.onnx和classes模型，Detector.onnx的模型约为139mb。如果该路径下的模型大小不合适，请删除该目录下的模型，重新启动 sd webui ，就会自动下载。
> 
> 2. C:\Users\用户所在目录\.insightface\models\buffalo_l
> 
> buffalo_l文件夹目录下有五个模型。您可以从下面的链接下载它们并将它们解压到 buffalo_l 目录中。
> 
> [https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip](Https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip)
> 
> 3. 下载[inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx)模型并将其放入 <webui_dir>/models/roop/ 目录中。

感谢，很有用，总算解决了这个问题

**Comment by 777Awesomesun** [comment]
This file  https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx was the same size as the one i already got. Still if i put it in the right folder, still most of my nsfw images are blocked by ROOP.

**Comment by 777Awesomesun** [comment]
Apparently there is a NSFW version for ROOP i'm downloading to try now. https://github.com/Gourieff/sd-webui-roop-nsfw

**Comment by yzufardiansyah** [comment]
> I found that it was caused by an error in the process of downloading the model. Make sure there are these models under the three paths below. If you don't have these folders, you can first create related folders according to the path below.
> 
> 1. C:\ Users\ directory where the user resides\ .ifnude
> 
> There are detector.onnx and classes models under this path, and the model of detector.onnx is about 139mb. If the model under this path is not the right size, please delete the model in the directory, restart sd webui ，It will download automatically.
> 
> 2. C:\ Users\ directory where the user resides\ .insightface\ models\ buffalo_l
> 
> There are five models in the buffalo_l folder directory. You can download them from the link below and extract them to the buffalo_l directory.
> 
> [Https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip](Https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip)
> 
> 3. download the [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx) model and put it inside <webui_dir>/models/roop/ directory.

Thank You, ITs WORK,

**Comment by raiyan22** [comment]
> I found that it was caused by an error in the process of downloading the model. Make sure there are these models under the three paths below. If you don't have these folders, you can first create related folders according to the path below.
> 
> 1. C:\ Users\ directory where the user resides\ .ifnude
> 
> There are detector.onnx and classes models under this path, and the model of detector.onnx is about 139mb. If the model under this path is not the right size, please delete the model in the directory, restart sd webui ，It will download automatically.
> 
> 2. C:\ Users\ directory where the user resides\ .insightface\ models\ buffalo_l
> 
> There are five models in the buffalo_l folder directory. You can download them from the link below and extract them to the buffalo_l directory.
> 
> [Https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip](Https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip)
> 
> 3. download the [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx) model and put it inside <webui_dir>/models/roop/ directory.

Thank you very much! It is working!!

**Comment by tolinescu** [comment]
Thanks, unfortunately i cannot find the [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx)

**Comment by niubiwang** [comment]
> 将[https://huggingface.co/s0md3v/nudity-checker/resolve/main/](https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx) detector.onnx 重新下载到错误路径：
> C:\Users\Admin.ifnude/ detector.onnx

太感谢了！！！！解决了，这是我第一次从这上面解决了问题

**Comment by iielse** [comment]
@tolinescu same, i cannot find the  [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx) too.

**Comment by Lu7-H** [comment]
大家检查一下pretrained_models的模型大小对不对，如果.onnx模型大小单位为byte，那就是git下来的模型有问题，正常应该是几十M，建议创建python文件，从modelscope下载模型。you should check the size of pretrained_models,if .onnx's size is kb,it means the size is not right,you can delete the pretrained_models fold and dowload it by followed in python
# SDK模型下载
from modelscope import snapshot_download
snapshot_download('iic/CosyVoice-300M', local_dir='pretrained_models/CosyVoice-300M')
snapshot_download('iic/CosyVoice-300M-SFT', local_dir='pretrained_models/CosyVoice-300M-SFT')
snapshot_download('iic/CosyVoice-300M-Instruct', local_dir='pretrained_models/CosyVoice-300M-Instruct')
snapshot_download('iic/CosyVoice-ttsfrd', local_dir='pretrained_models/CosyVoice-ttsfrd')
