### ISSUE TITLE
Error after Roop: error loading script:api.py;cimage.py...

### ISSUE THREAD

**Issue by vtonio** [s0md3v/sd-webui-roop#292]
venv "C:\Users\vande\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Requirement already satisfied: insightface==0.7.3 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from -r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.7.3)
Requirement already satisfied: onnx==1.14.0 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from -r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 2)) (1.14.0)
Requirement already satisfied: onnxruntime==1.15.0 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from -r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: opencv-python==4.7.0.72 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from -r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 4)) (4.7.0.72)Requirement already satisfied: ifnude in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from -r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 5)) (0.0.3)
Requirement already satisfied: cython in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from -r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 6)) (3.0.7)
Requirement already satisfied: numpy in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.26.2)Requirement already satisfied: tqdm in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (4.66.1)
Requirement already satisfied: requests in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: matplotlib in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.8.2)
Requirement already satisfied: Pillow in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (10.1.0)
Requirement already satisfied: scipy in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.11.4)Requirement already satisfied: scikit-learn in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.3.2)
Requirement already satisfied: scikit-image in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.22.0)
Requirement already satisfied: easydict in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.11)
Requirement already satisfied: albumentations in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: prettytable in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.9.0)
Requirement already satisfied: protobuf>=3.20.2 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from onnx==1.14.0->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 2)) (4.25.1)
Requirement already satisfied: typing-extensions>=3.6.2.1 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from onnx==1.14.0->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 2)) (4.9.0)
Requirement already satisfied: coloredlogs in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from onnxruntime==1.15.0->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (15.0.1)
Requirement already satisfied: flatbuffers in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from onnxruntime==1.15.0->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (23.5.26)
Requirement already satisfied: packaging in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from onnxruntime==1.15.0->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (23.2)
Requirement already satisfied: sympy in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from onnxruntime==1.15.0->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (1.12)
Requirement already satisfied: opencv-python-headless>=4.5.1.48 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from ifnude->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 5)) (4.8.1.78)
Requirement already satisfied: PyYAML in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from albumentations->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: qudida>=0.0.4 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from albumentations->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.0.4)
Requirement already satisfied: networkx>=2.8 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: imageio>=2.27 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2.33.1)
Requirement already satisfied: tifffile>=2022.8.12 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2023.12.9)
Requirement already satisfied: lazy_loader>=0.3 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from scikit-image->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.3)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from coloredlogs->onnxruntime==1.15.0->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (4.46.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: wcwidth in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from prettytable->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.2.12)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from requests->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from requests->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from requests->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from requests->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2023.11.17)
Requirement already satisfied: joblib>=1.1.1 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from sympy->onnxruntime==1.15.0->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: colorama in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from tqdm->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: pyreadline3 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime==1.15.0->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (3.4.1)
Requirement already satisfied: six>=1.5 in c:\users\vande\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3->-r C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.16.0)
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
*** Error loading script: api.py
    Traceback (most recent call last):
      File "C:\Users\vande\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\vande\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\scripts\api.py", line 17, in <module>
        from scripts.faceswap import get_models
      File "C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

---
*** Error loading script: cimage.py
    Traceback (most recent call last):
      File "C:\Users\vande\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\vande\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "C:\Users\vande\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\vande\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

---
2023-12-22 15:11:01,839 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "C:\Users\vande\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\vande\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\vande\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 13, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

---
Loading weights [cc6cb27103] from C:\Users\vande\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.ckptRunning on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 10.5s (prepare environment: 3.2s, import torch: 2.8s, import gradio: 0.9s, setup paths: 0.8s, initialize shared: 0.2s, other imports: 0.5s, setup codeformer: 0.1s, load scripts: 1.2s, create ui: 0.4s, gradio launch: 0.3s).
Creating model from config: C:\Users\vande\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 5.9s (load weights from disk: 2.3s, create model: 0.6s, apply weights to model: 2.7s, calculate empty prompt: 0.1s).

**Comment by vtonio** [comment]
I turn around, thanks

**Comment by vtonio** [comment]
I installed Reactor instead but I don't have the faceswap option appearing. A solution?
![Capture](https://github.com/s0md3v/sd-webui-roop/assets/154610203/f85cc033-d3c6-463d-993b-0b5681a83137)
![Capture1](https://github.com/s0md3v/sd-webui-roop/assets/154610203/336e8339-6d54-4728-b2d0-d7ac9134eb3c)
venv "C:\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.006892200006404892
ReActor preheating... Device: CUDA
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
14:43:06 - ReActor - STATUS - Running v0.6.0-a4
Loading weights [6ce0161689] from C:\webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: C:\webui\configs\v1-inference.yaml
Startup time: 12.2s (prepare environment: 3.9s, import torch: 2.8s, import gradio: 0.9s, setup paths: 0.8s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 1.9s, create ui: 0.4s, gradio launch: 0.6s).
Applying attention optimization: Doggettx... done.
Model loaded in 4.8s (load weights from disk: 0.7s, create model: 0.3s, apply weights to model: 3.0s, calculate empty prompt: 0.5s).

**Comment by CrimoMX** [comment]
Hello friend, how did you fix the problem of "ModuleNotFoundError: No module named 'ifnude'" I'm stuck right there. (Didnt see your issue before, I've just posted the same issue).
