### ISSUE TITLE
cannot import name 'Undefined' from 'pydantic.fields after add the roop extension 

### ISSUE THREAD

**Issue by ForLuna1998** [s0md3v/sd-webui-roop#306]
Using cached protobuf-5.27.3-cp310-abi3-win_amd64.whl (426 kB)
Using cached pydantic-2.8.2-py3-none-any.whl (423 kB)
Installing collected packages: protobuf, pydantic
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.0
    Uninstalling protobuf-3.20.0:
      Successfully uninstalled protobuf-3.20.0
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.17
    Uninstalling pydantic-1.10.17:
      Successfully uninstalled pydantic-1.10.17
Successfully installed protobuf-5.27.3 pydantic-2.8.2
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\launch.py", line 44, in main
    start()
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\modules\launch_utils.py", line 465, in start
    import webui
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\modules\initialize.py", line 23, in imports
    import gradio  # noqa: F401
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\venv\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\venv\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\venv\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (C:\Users\Long'Min\Desktop\yd\stable-diffusion-webui\venv\lib\site-packages\pydantic\fields.py)

**Comment by Comput3rUs3r** [comment]
Having the same error. I used to use this extension last year and worked fine. I just tried to use with with a new a1111 installation and this is what is happening.

**Comment by william20210206** [comment]
use Reactor, roop got some thing wrong these days, and for a long time didn't have a update
