### ISSUE TITLE
ImportError: cannot import name 'ImageResult' 

### ISSUE THREAD

**Issue by nlienard** [s0md3v/sd-webui-roop#31]
hi,

I m running roop as well separately, meaning i got python and C++ as well.

But for the extension, i got this error:

```
Error loading script: faceswap.py
Traceback (most recent call last):
  File "C:\IA\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\IA\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\IA\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 15, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
ImportError: cannot import name 'ImageResult' from 'scripts.swapper' (C:\IA\stable-diffusion-webui\extensions\sd-webui-faceswap\scripts\swapper.py)
```

Any clue is welcome.

thanks

**Comment by DefNotYashar** [comment]
same here

**Comment by nlienard** [comment]
finally i fixed this issue by disabling another extension "sd-web-faceswap" which was in conflict together I guess.
