### ISSUE TITLE
When I enable faceswap , then it report following error

### ISSUE THREAD

**Issue by eu09** [s0md3v/sd-webui-roop#34]
Error running postprocess_batch: /stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/scripts.py", line 496, in postprocess_image
webui-docker-auto-1  |     script.postprocess_image(p, pp, *script_args)
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 184, in postprocess_image
webui-docker-auto-1  |     result: ImageResult = swap_face(
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 125, in swap_face
webui-docker-auto-1  |     source_face = get_face_single(source_img, face_index=0)
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 78, in get_face_single
webui-docker-auto-1  |     face_analyser = copy.deepcopy(ANALYSIS_MODEL)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
webui-docker-auto-1  |     y = _reconstruct(x, memo, *rv)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
webui-docker-auto-1  |     state = deepcopy(state, memo)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
webui-docker-auto-1  |     y = copier(x, memo)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
webui-docker-auto-1  |     y[deepcopy(key, memo)] = deepcopy(value, memo)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
webui-docker-auto-1  |     y = copier(x, memo)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
webui-docker-auto-1  |     y[deepcopy(key, memo)] = deepcopy(value, memo)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
webui-docker-auto-1  |     y = _reconstruct(x, memo, *rv)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
webui-docker-auto-1  |     state = deepcopy(state, memo)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
webui-docker-auto-1  |     y = copier(x, memo)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
webui-docker-auto-1  |     y[deepcopy(key, memo)] = deepcopy(value, memo)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
webui-docker-auto-1  |     y = _reconstruct(x, memo, *rv)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/copy.py", line 273, in _reconstruct
webui-docker-auto-1  |     y.__setstate__(state)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 33, in __setstate__
webui-docker-auto-1  |     self.__init__(model_path)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
webui-docker-auto-1  |     super().__init__(model_path, **kwargs)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 396, in __init__
webui-docker-auto-1  |     raise e
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
webui-docker-auto-1  |     self._create_inference_session(providers, provider_options, disabled_optimizers)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 415, in _create_inference_session
webui-docker-auto-1  |     raise ValueError(
webui-docker-auto-1  | ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by ErwannMillon** [comment]
Hey there, 
Would you mind sharing the fix? I'm still getting this error trying to run roop with CUDA acceleration in a python 3.9 conda env with the requirements installed per requirements.txt, on Ubunutu 20.04. 

Thanks for the great work :)
