### ISSUE TITLE
Error (Didn't follow the instructions)

### ISSUE THREAD

**Issue by soloist-tech** [s0md3v/sd-webui-roop#36]
I'm sorry but I made a mistake, first I found the extension on the stabile diffusion UI and installed it from there. It didn't do anything so I checked the repo. Then I saw visual studio was needed so I installed that according to the requirements. 

Now I get roop and can attempt to use it but it doesn't work and I get this error:

Error running postprocess_batch: C:\Users\Robby\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "C:\Users\Username\Documents\GitHub\stable-diffusion-webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "C:\Users\Username\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 181, in postprocess_image
    if self.enable and self.swap_in_generated:
AttributeError: 'FaceSwapScript' object has no attribute 'enable'

What can I do? I'd like to delete the extension and add again but I don't see the option. I could delete the folder?

More errors:

2023-06-21 11:17:09,980 - roop - INFO - roop v0.0.2
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Username/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Username/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Username/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Username/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Username/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Error calling: C:\Users\Username\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py/ui
Traceback (most recent call last):
  File "C:\Users\Username\Documents\GitHub\stable-diffusion-webui\modules\scripts.py", line 283, in wrap_call
    res = func(*args, **kwargs)
  File "C:\Users\Username\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 64, in ui
    models = get_models()
  File "C:\Users\Username\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 21, in get_models
    models = glob.glob(models_path)
UnboundLocalError: local variable 'models_path' referenced before assignment

Error calling: C:\Users\Username\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py/ui
Traceback (most recent call last):
  File "C:\Users\Username\Documents\GitHub\stable-diffusion-webui\modules\scripts.py", line 283, in wrap_call
    res = func(*args, **kwargs)
  File "C:\Users\Username\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 64, in ui
    models = get_models()
  File "C:\Users\Username\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 21, in get_models
    models = glob.glob(models_path)
UnboundLocalError: local variable 'models_path' referenced before assignment

**Comment by onlinegamez** [comment]
I get the same errors.

**Comment by soloist-tech** [comment]
> I get the same errors.

Did you follow the same installation process as me? If not the problem might be actual code problems rather than an installation failure.

**Comment by onlinegamez** [comment]
I  guess. But I just found the solution from the other Thread: https://github.com/s0md3v/sd-webui-roop/issues/33#issuecomment-1601149721

It worked for me.

**Comment by soloist-tech** [comment]
> I guess. But I just found the solution from the other Thread: [#33 (comment)](https://github.com/s0md3v/sd-webui-roop/issues/33#issuecomment-1601149721)
> 
> It worked for me.

Totally worked, I didn't think it was a code problem. Thanks!
