### ISSUE TITLE
Face swap py error/ traceback error

### ISSUE THREAD

**Issue by Katvision** [s0md3v/sd-webui-roop#39]
Error calling: /Users/devinketchens/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py/ui
Traceback (most recent call last):
  File "/Users/devinketchens/stable-diffusion-webui/modules/scripts.py", line 271, in wrap_call
    res = func(*args, **kwargs)
  File "/Users/devinketchens/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 64, in ui
    models = get_models()
  File "/Users/devinketchens/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 21, in get_models
    models = glob.glob(models_path)
UnboundLocalError: local variable 'models_path' referenced before assignment

Error calling: /Users/devinketchens/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py/ui
Traceback (most recent call last):
  File "/Users/devinketchens/stable-diffusion-webui/modules/scripts.py", line 271, in wrap_call
    res = func(*args, **kwargs)
  File "/Users/devinketchens/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 64, in ui
    models = get_models()
  File "/Users/devinketchens/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 21, in get_models
    models = glob.glob(models_path)
UnboundLocalError: local variable 'models_path' referenced before assignment

**Comment by FxUK** [comment]
https://github.com/s0md3v/sd-webui-roop/issues/33#issuecomment-1601149721

**Comment by s0md3v** [comment]
Fixed.

**Comment by Katvision** [comment]
Thanks this worked.
