### ISSUE TITLE
my roop just run in first time

### ISSUE THREAD

**Issue by pikabooi** [s0md3v/sd-webui-roop#43]
my roop just run first time, and if i closed SD, and run webuser.bat again, this extension is gone in SD tab

**Comment by ToTheTopYo** [comment]
What arguments are you using?

**Comment by s0md3v** [comment]
Please post any errors you got in your terminal here. It is impossible to figure out what happened on your machine.

**Comment by pikabooi** [comment]
hi dude, 
i got this error, and try to solve with traceback (most recent call) in older post issues, and not solved
--------------------------------
Error loading script: swapper.py
Traceback (most recent call last):
  File "C:\Stable Difusion\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Stable Difusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Stable Difusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
    import insightface
  File "C:\Stable Difusion\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "C:\Stable Difusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "C:\Stable Difusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "C:\Stable Difusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
----------------------------------------------

**Comment by pikabooi** [comment]
hi dude, 
i got this error, and try to solve with [traceback (most recent call)](https://github.com/s0md3v/sd-webui-roop/issues/33#) in older post issues, and not solved
--------------------------------
Error loading script: swapper.py
Traceback (most recent call last):
  File "C:\Stable Difusion\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Stable Difusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Stable Difusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
    import insightface
  File "C:\Stable Difusion\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "C:\Stable Difusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "C:\Stable Difusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "C:\Stable Difusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
----------------------------------------------
