### ISSUE TITLE
FaceSwapScript.postprocess_batch() got multiple values for argument 'images'

### ISSUE THREAD

**Issue by ipinz** [s0md3v/sd-webui-roop#52]
Error running postprocess_batch: D:\_AI_stableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "D:\_AI_stableDiffusion\stable-diffusion-webui\modules\scripts.py", line 487, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: FaceSwapScript.postprocess_batch() got multiple values for argument 'images'

Error running postprocess_batch: D:\_AI_stableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "D:\_AI_stableDiffusion\stable-diffusion-webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "D:\_AI_stableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 183, in postprocess_image
    result: ImageResult = swap_face(
  File "D:\_AI_stableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 111, in swap_face
    converted = convert_to_sd(target_img)
  File "D:\_AI_stableDiffusion\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 6, in convert_to_sd
    chunks = detect(img)
  File "D:\_AI_stableDiffusion\stable-diffusion-webui\venv\lib\site-packages\ifnude\detector.py", line 46, in detect
    detection_model = onnxruntime.InferenceSession(model_path, providers=["CPUExecutionProvider"])
  File "D:\_AI_stableDiffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\_AI_stableDiffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\Administrator\.ifnude/detector.onnx failed:Protobuf parsing failed.

**Comment by s0md3v** [comment]
This should be fixed now.

**Comment by s0md3v** [comment]
@MaximilianPs pushed another fix, let me know if it works.

**Comment by MaximilianPs** [comment]
Wow, amazingly fast!
Yes, it's fine now, thank you man!!! ;-)

Sasha Gray as Spiderman (prompt in Meta)
![image](https://github.com/s0md3v/sd-webui-roop/assets/23430638/5ac6d1a6-57cd-40fd-8e8a-fc7d2974cc21)
