### ISSUE TITLE
Error upon installing Roop Extension - Any idea?

### ISSUE THREAD

**Issue by gunia10** [s0md3v/sd-webui-roop#58]
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Install ifnude
Installing sd-webui-roop requirement: ifnude

Launching Web UI with arguments: --api --xformers
Traceback (most recent call last):
  File "D:\AI\SUPERSD\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 2872, in get_entry_map
    ep_map = self._ep_map
  File "D:\AI\SUPERSD\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 2834, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map. Did you mean: '_dep_map'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\SUPERSD\stable-diffusion-webui\launch.py", line 370, in <module>
    start()
  File "D:\AI\SUPERSD\stable-diffusion-webui\launch.py", line 361, in start
    import webui
  File "D:\AI\SUPERSD\stable-diffusion-webui\webui.py", line 37, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "D:\AI\SUPERSD\stable-diffusion-webui\modules\ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "D:\AI\SUPERSD\stable-diffusion-webui\modules\ui_extra_networks.py", line 8, in <module>
    from modules.images import read_info_from_image
  File "D:\AI\SUPERSD\stable-diffusion-webui\modules\images.py", line 16, in <module>
    from fonts.ttf import Roboto
  File "D:\AI\SUPERSD\stable-diffusion-webui\venv\lib\site-packages\fonts\ttf\__init__.py", line 5, in <module>
    for entry_point in pkg_resources.iter_entry_points('fonts_ttf'):
  File "D:\AI\SUPERSD\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 662, in <genexpr>
    for entry in dist.get_entry_map(group).values()
  File "D:\AI\SUPERSD\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 2874, in get_entry_map
    ep_map = self._ep_map = EntryPoint.parse_map(
  File "D:\AI\SUPERSD\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py", line 2559, in parse_map
    raise ValueError("Entry points must be listed in groups")
ValueError: Entry points must be listed in groups
Press any key to continue . . .

**Comment by s0md3v** [comment]
This error is not related to roop, its inside code of webui.

Try updating webui and python.
