### ISSUE TITLE
install.py, ifnude, and some other things wont install

### ISSUE THREAD

**Issue by trxsudo** [s0md3v/sd-webui-roop#6]
Error running install.py for extension D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-roop.
Command: "D:\sd\sd-webui-aki-v4.1\python\python.exe" "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-roop\install.py"
Error code: 1
stdout: Check roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install tensorflow==2.12.0
Installing sd-webui-roop requirement: tensorflow==2.12.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Install ifnude
Installing sd-webui-roop requirement: ifnude
Couldn't install sd-webui-roop requirement: ifnude.
Command: "D:\sd\sd-webui-aki-v4.1\python\python.exe" -m pip install ifnude --prefer-binary --index-url https://mirror.baidu.com/pypi/simple
Error code: 1
stdout: Looking in indexes: https://mirror.baidu.com/pypi/simple, https://mirrors.aliyun.com/pypi/simple
Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html

stderr: ERROR: Could not find a version that satisfies the requirement ifnude (from versions: none)
ERROR: No matching distribution found for ifnude

Warning: Failed to install ifnude, roop will not work.

stderr: Traceback (most recent call last):
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-roop\install.py", line 44, in <module>
    raise e
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-roop\install.py", line 26, in <module>
    launch.run_pip(
  File "D:\sd\sd-webui-aki-v4.1\modules\launch_utils.py", line 124, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "D:\sd\sd-webui-aki-v4.1\modules\launch_utils.py", line 101, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install sd-webui-roop requirement: ifnude.

Command: "D:\sd\sd-webui-aki-v4.1\python\python.exe" -m pip install ifnude --prefer-binary --index-url https://mirror.baidu.com/pypi/simple
Error code: 1
stdout: Looking in indexes: https://mirror.baidu.com/pypi/simple, https://mirrors.aliyun.com/pypi/simple
Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html

stderr: ERROR: Could not find a version that satisfies the requirement ifnude (from versions: none)
ERROR: No matching distribution found for ifnude

Installing requirements for TemporalKit extension

Launching Web UI with arguments: --theme dark --xformers --no-half-vae --api --autolaunch
[-] ADetailer initialized. version: 23.6.2, num models: 8
[AddNet] Updating model hashes...

[AddNet] Updating model hashes...

2023-06-19 06:46:55,455 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\annotator\downloads
2023-06-19 06:46:55,549 - ControlNet - INFO - ControlNet v1.1.224
Loading weights [ecefb796ff] from D:\sd\sd-webui-aki-v4.1\models\Stable-diffusion\neverendingDreamNED_v122BakedVae.safetensors
Creating model from config: D:\sd\sd-webui-aki-v4.1\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Couldn't find VAE named vae-ft-mse-840000-ema-pruned.safetensors; using None instead
Textual inversion embeddings loaded(1): EasyNegative
Model loaded in 4.2s (load weights from disk: 0.6s, create model: 0.3s, apply weights to model: 1.9s, apply half(): 0.5s, move model to device: 0.8s).
Error loading script: cimage.py
Traceback (most recent call last):
  File "D:\sd\sd-webui-aki-v4.1\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\sd\sd-webui-aki-v4.1\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
ModuleNotFoundError: No module named 'ifnude'

Error loading script: faceswap.py
Traceback (most recent call last):
  File "D:\sd\sd-webui-aki-v4.1\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\sd\sd-webui-aki-v4.1\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-roop\scripts\faceswap.py", line 15, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
    from scripts.cimage import convert_to_sd
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
ModuleNotFoundError: No module named 'ifnude'

2023-06-19 06:47:01,046 - roop - INFO - roop v0.0.1
Error loading script: swapper.py
Traceback (most recent call last):
  File "D:\sd\sd-webui-aki-v4.1\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\sd\sd-webui-aki-v4.1\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
    from scripts.cimage import convert_to_sd
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
ModuleNotFoundError: No module named 'ifnude'

cant seem to install ifnude and other things. how to fix?

**Comment by s0md3v** [comment]
Update the extension and try again. If that doesn't work, install it manually with `pip install -r requirements.txt`

**Comment by lingkops4** [comment]
install it manually with pip install ifnude --upgrade  I that doesn't work
i downloda fnude.zip pull in stable-diffusion-webui-master9\venv\Lib\site-packages 
 **ifnude.egg-info**and **ifnude** 
![螢幕擷取畫面 2024-05-27 235751](https://github.com/s0md3v/sd-webui-roop/assets/148435004/1006f7cb-704e-407e-8bc1-7b5585b013be)
