### ISSUE TITLE
Error loading script: swapper.py:ModuleNotFoundError: No module named 'insightface'

### ISSUE THREAD

**Issue by alinasama** [s0md3v/sd-webui-roop#66]
I have installed insightface by cmd run "pip install insightface". however, I still got this issue when using webui:

Error loading script: swapper.py
Traceback (most recent call last):
  File "F:\novelai-webui-aki-v2\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\novelai-webui-aki-v2\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\novelai-webui-aki-v2\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

**Comment by s0md3v** [comment]
install insightface library.
