### ISSUE TITLE
Roop didn't start because modules are not found

### ISSUE THREAD

**Issue by alexandregoes** [s0md3v/sd-webui-roop#67]
I got some log lines as "ModuleNotFoundError: No module named 'nameofthemodule'"
So I tried to install them using PowerShell and cmd.

Apparently missing modules:
pip install insightface==0.7.3 (1st time it was installed. Now the return are a lot of lines with "Requirement already satisfied)
pip install ifnude (same)
pip install _socket (ERROR: Invalid requirement: '_socket')

Here is the full log:
----------------------------------------
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing requirements

Error running install.py for extension C:\AI\sd.webui\webui\extensions\sd-webui-roop.
Command: "C:\AI\sd.webui\system\python\python.exe" "C:\AI\sd.webui\webui\extensions\sd-webui-roop\install.py"
Error code: 1
stdout: Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Couldn't install sd-webui-roop requirement: insightface==0.7.3.
Command: "C:\AI\sd.webui\system\python\python.exe" -m pip install insightface==0.7.3 --prefer-binary
Error code: 2
stdout: Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'

stderr: ERROR: Exception:
Traceback (most recent call last):
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 631, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 692, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\alexa\AppData\Local\Temp\pip-build-env-4hxvifeh\overlay\Lib\site-packages\setuptools\__init__.py", line 15, in <module>
    import setuptools.version
  File "C:\Users\alexa\AppData\Local\Temp\pip-build-env-4hxvifeh\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
    from ._importlib import metadata
  File "C:\Users\alexa\AppData\Local\Temp\pip-build-env-4hxvifeh\overlay\Lib\site-packages\setuptools\_importlib.py", line 44, in <module>
    import importlib.metadata as metadata  # noqa: F401
  File "importlib\metadata\__init__.py", line 17, in <module>
  File "importlib\metadata\_adapters.py", line 3, in <module>
  File "email\message.py", line 15, in <module>
  File "email\utils.py", line 29, in <module>
  File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'

Warning: Failed to install insightface==0.7.3, roop will not work.

stderr: Traceback (most recent call last):
  File "C:\AI\sd.webui\webui\extensions\sd-webui-roop\install.py", line 54, in <module>
    raise e
  File "C:\AI\sd.webui\webui\extensions\sd-webui-roop\install.py", line 36, in <module>
    launch.run_pip(
  File "C:\AI\sd.webui\webui\modules\launch_utils.py", line 124, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "C:\AI\sd.webui\webui\modules\launch_utils.py", line 101, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install sd-webui-roop requirement: insightface==0.7.3.
Command: "C:\AI\sd.webui\system\python\python.exe" -m pip install insightface==0.7.3 --prefer-binary
Error code: 2
stdout: Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'

stderr: ERROR: Exception:
Traceback (most recent call last):
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 631, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 692, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:\AI\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\alexa\AppData\Local\Temp\pip-build-env-4hxvifeh\overlay\Lib\site-packages\setuptools\__init__.py", line 15, in <module>
    import setuptools.version
  File "C:\Users\alexa\AppData\Local\Temp\pip-build-env-4hxvifeh\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
    from ._importlib import metadata
  File "C:\Users\alexa\AppData\Local\Temp\pip-build-env-4hxvifeh\overlay\Lib\site-packages\setuptools\_importlib.py", line 44, in <module>
    import importlib.metadata as metadata  # noqa: F401
  File "importlib\metadata\__init__.py", line 17, in <module>
  File "importlib\metadata\_adapters.py", line 3, in <module>
  File "email\message.py", line 15, in <module>
  File "email\utils.py", line 29, in <module>
  File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'

Launching Web UI with arguments: --xformers
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
2023-06-23 03:32:50,182 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: C:\AI\sd.webui\webui\extensions\sd-webui-controlnet\annotator\downloads
2023-06-23 03:32:50,345 - ControlNet - INFO - ControlNet v1.1.224
Loading weights [0981b250eb] from C:\AI\sd.webui\webui\models\Stable-diffusion\eroticVision_v3.safetensors
Creating model from config: C:\AI\sd.webui\webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Textual inversion embeddings loaded(2): bad-hands-5, easynegative
Model loaded in 3.0s (load weights from disk: 0.3s, create model: 0.7s, apply weights to model: 0.7s, apply half(): 0.7s, move model to device: 0.6s).
Error loading script: cimage.py
Traceback (most recent call last):
  File "C:\AI\sd.webui\webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AI\sd.webui\webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\sd.webui\webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
ModuleNotFoundError: No module named 'ifnude'

Error loading script: faceswap.py
Traceback (most recent call last):
  File "C:\AI\sd.webui\webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AI\sd.webui\webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\sd.webui\webui\extensions\sd-webui-roop\scripts\faceswap.py", line 15, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "C:\AI\sd.webui\webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

2023-06-23 03:32:55,455 - roop - INFO - roop v0.0.2
Error loading script: swapper.py
Traceback (most recent call last):
  File "C:\AI\sd.webui\webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AI\sd.webui\webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\sd.webui\webui\extensions\sd-webui-roop\scripts\swapper.py", line 12, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

Applying optimization: xformers... done.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 13.9s (import torch: 2.2s, import gradio: 1.7s, import ldm: 0.6s, other imports: 1.2s, setup codeformer: 0.1s, load scripts: 7.3s, create ui: 0.5s, gradio launch: 0.2s).

----------------------------------------

Any ideas on how to solve it?

**Comment by s0md3v** [comment]
install them.

**Comment by alexandregoes** [comment]
I tried to do it.  Look at the start of my message the commands I did and my comments.

pip install insightface==0.7.3

1st time it was installed with no errors. Now the return are a lot of lines with "Requirement already satisfied". So, it's already installed, right?  If not, could you please tell me how?

pip install ifnude

Same as above.

pip install _socket

I get the message: ERROR: Invalid requirement: '_socket'
