### ISSUE TITLE
Roop doesn't work.

### ISSUE THREAD

**Issue by liuhaowei-littlebird** [s0md3v/sd-webui-roop#73]
I deployed sd on the GPU cloud server of A5000, the python version in the cloud is 3.8, the OS is Linux. I installed insightface==0.7.3, it is invalid after enabling roop in sd, is there any dependency I am missing?Just to emphasize, I promise that my images are not NSFW.

**Comment by enzyme69** [comment]
I also can confirm that the roop faceswap does not work at all on macOS, but the standalone roop works on my side. So the extension has bug.

**Comment by s0md3v** [comment]
Always post your terminal output while submitting bugs. It is not possible for it to not swap face on a working installation.

**Comment by liuhaowei-littlebird** [comment]
> Always post your terminal output while submitting bugs. It is not possible for it to not swap face on a working installation.

Error running postprocess_batch: /root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/scripts.py", line 422, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 183, in postprocess_image
    result: ImageResult = swap_face(
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 109, in swap_face
    converted = convert_to_sd(target_img)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-roop/scripts/cimage.py", line 6, in convert_to_sd
    chunks = detect(img)
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/ifnude/detector.py", line 46, in detect
    detection_model = onnxruntime.InferenceSession(model_path, providers=["CPUExecutionProvider"])
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /root/.ifnude/detector.onnx failed:Protobuf parsing failed.
