### ISSUE TITLE
faceswap.py : got an unexpected keyword argument 'providers'

### ISSUE THREAD

**Issue by wilsto** [s0md3v/sd-webui-roop#80]
Thanks for this awesome tools, i have an error when i want to use use

2023-06-23 21:48:32 Error running postprocess_batch: /stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
2023-06-23 21:48:32 Traceback (most recent call last):
2023-06-23 21:48:32   File "/stable-diffusion-webui/modules/scripts.py", line 496, in postprocess_image
2023-06-23 21:48:32     script.postprocess_image(p, pp, *script_args)
2023-06-23 21:48:32   File "/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 183, in postprocess_image
2023-06-23 21:48:32     result: ImageResult = swap_face(
2023-06-23 21:48:32   File "/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 123, in swap_face
2023-06-23 21:48:32     source_face = get_face_single(source_img, face_index=0)
2023-06-23 21:48:32   File "/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 76, in get_face_single
2023-06-23 21:48:32     face_analyser = insightface.app.FaceAnalysis(name="buffalo_l", providers=providers)
2023-06-23 21:48:32 TypeError: FaceAnalysis.__init__() got an unexpected keyword argument 'providers'

this is a how i configure roop:
![image](https://github.com/s0md3v/sd-webui-roop/assets/4889715/eefc43ba-4fa4-4160-97d7-dc247f13997d)

**Comment by s0md3v** [comment]
You are using an outdated version of insightface. Installation issues are out of scope.

**Comment by wilsto** [comment]
Thanks for your quick help. It works with the right version.
