### ISSUE TITLE
Stable diffusion roop extension error

### ISSUE THREAD

**Issue by 1ules** [s0md3v/sd-webui-roop#91]
Error running postprocess_batch: D:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
    result: ImageResult = swap_face(
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 123, in swap_face
    source_face = get_face_single(source_img, face_index=0)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 76, in get_face_single
    face_analyser = insightface.app.FaceAnalysis(name="buffalo_l", providers=providers)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\app\face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\utils\storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\utils\storage.py", line 17, in download
    download_file(model_url,
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\utils\download.py", line 68, in download_file
    os.makedirs(dirname)
  File "C:\Users\Jules\AppData\Local\Programs\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Jules\AppData\Local\Programs\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Jules\AppData\Local\Programs\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "C:\Users\Jules\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\AI\\stable-diffusion-webui\x0benv'

**Comment by LanguagesMan** [comment]
Hey, I experience the same issue as well... Did you solve this? It would help a lot!! Thanks
