### ISSUE TITLE
Help me to solve the Error I want to use it.(roop)

### ISSUE THREAD

**Issue by chalitc** [s0md3v/sd-webui-roop#94]
Error running postprocess_batch: D:\SD_NEW\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py3.00it/s]
Traceback (most recent call last):
  File "D:\SD_NEW\stable-diffusion-webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "D:\SD_NEW\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
    result: ImageResult = swap_face(
  File "D:\SD_NEW\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 123, in swap_face
    source_face = get_face_single(source_img, face_index=0)
  File "D:\SD_NEW\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 76, in get_face_single
    face_analyser = insightface.app.FaceAnalysis(name="buffalo_l", providers=providers)
  File "D:\SD_NEW\stable-diffusion-webui\venv\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

How do I fix the problem?

**Comment by CreativeTerry** [comment]
Same Error with me also... If you will get any information to solve then please help me also...

**Comment by YMC-GitHub** [comment]
Same Error with me

**Comment by 6802332123** [comment]
fixed the issue by doing below:
1.  download [buffalo_l.zip](https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip) 
2. copy buffalo_l.zip to C:\Users\you_user_name\.insightface\models\buffalo_l and extract the same dir
3. restart roop
