### ISSUE TITLE
Downloading the detection model to C:\Users\dckf\.models/detector.onnx，error。help me。get me a   detector.onnx   download url。tk!

### ISSUE THREAD

**Issue by swumagic** [s0md3v/sd-webui-roop#96]
help me!get me a   detector.onnx   download url。tk!
Downloading the detection model to C:\Users\dckf\.models/detector.onnx
Error loading script: cimage.py
Traceback (most recent call last):
  File "M:\SD\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\SD\sdwebui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
    from ifnude import detect
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\__init__.py", line 1, in <module>
    from .detector import detect
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 35, in <module>
    download(model_url, model_path)
  File "M:\SD\sdwebui\py310\lib\site-packages\ifnude\detector.py", line 15, in download
    request = urllib.request.urlopen(url)
NameError: name 'urllib' is not defined
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by k186** [comment]
你如果用的集合包， 在设置里面代理设置 的代理服务器地址改为你的本地代理端口就可以了

**Comment by Tongzhou-Yu** [comment]
这里：https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx

**Comment by WrathofGod** [comment]
> 这里：https://huggingface.co/s0md3v/nudity-checker/resolve/main/detector.onnx

i can't get it, This website cannot be accessed
